/***********************************************************************************************************************
 * File Name    : custom_guard.c
 * Description  : Custom non-secure callable function header.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#ifndef CUSTOM_GUARD_H_
#define CUSTOM_GUARD_H_

#include "hal_data.h"

/* This macro is used to enable/disable unused non-secure callable functions generated by FSP */
#define UNUSED_GUARD_ON (0x0U)

#endif /* CUSTOM_GUARD_H_ */
