/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "i3c_slave_ep.h"

/*******************************************************************************************************************//**
 * @addtogroup i3c_slave_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* To capture the status(Success/Failure) of each Function/API. */
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);
    APP_PRINT(BANNER_INFO,EP_VERSION,version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch );
    APP_PRINT(EP_INFO);

    /* Initialize AGT driver */
    err = R_AGT_Open(&g_timeout_timer_ctrl, &g_timeout_timer_cfg);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\nERROR : R_AGT_Open API FAILED \r\n");
        APP_ERR_TRAP(err);
    }

    /* Initialize ICU driver */
    err = icu_init();
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\nERROR : icu_init function failed.\r\n");
        /* de-initialize the opened AGT timer module.*/
        agt_deinit();
        APP_ERR_TRAP(err);
    }

    /* Initialize I3C slave device.*/
    err = i3c_slave_init();
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\nERROR : i3c_slave_init function failed.\r\n");
        /* de-initialize the opened AGT timer and ICU modules.*/
        agt_deinit();
        icu_deinit();
        APP_ERR_TRAP(err);
    }

    while(true)
    {
        /* Perform I3C slave operation.*/
        err = i3c_slave_ops();
        if (FSP_SUCCESS != err)
        {
            APP_ERR_PRINT ("\r\nERROR : init_i3c_slave function failed.\r\n");
            /* de-initialize the opened AGT timer, I3C and ICU modules.*/
            agt_deinit();
            icu_deinit();
            i3c_deinit();
            APP_ERR_TRAP(err);
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup i3c_slave_ep)
 **********************************************************************************************************************/
