/***********************************************************************************************************************
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
************************************************************************************************************************/

#include "hal_data.h"
#include "app_definitions.h"
#include "crypto_operations.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

void print_main_menu(void);

/*****************************************************************************************************************
 *  @brief      print_main_menu
 *              This function prints the user menu.
 *  @retval     none
 *  ****************************************************************************************************************/
void print_main_menu(void)
{
    APP_PRINT(MENUOPTION_MENU);

    /* Menu for User Selection */
    APP_PRINT(MENUOPTION1);
    APP_PRINT(MENUOPTION2);
    APP_PRINT(MENUOPTION3);
    APP_PRINT(MENUOPTION4);
    APP_PRINT(MENUOPTION5);
    APP_PRINT(MENUOPTION6);
}
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    bool result = false;
    print_main_menu();
    uint8_t readBuff[BUFF_SIZE] =  { RESET_VALUE };

    while(true)
    {
        /* check if there is user manual item selection or button press on S1 */
        if (APP_CHECK_DATA)
        {

            uint32_t rByte = APP_READ(readBuff);

            /* function returns the converted integral number as an int value.*/
            int32_t inputRead = atoi((char *)readBuff);

            if (rByte > RESET_VALUE)
            {
                switch (inputRead)
                {
                    case DECRYPT_WITH_INJECTED_AES_KEY:
                    {
                        APP_PRINT(MENUEVENT1);
                        result = cipher_operation_with_directly_injected_aes_key();
                        if(true==result)
                        {
                            APP_PRINT(RESULT1_SUCCESS);
                        }
                        else
                        {
                            APP_PRINT(RESULT1_FAILURE);
                        }
                        print_main_menu();
                    }
                    break;
                    case UPDATE_AES_KEY:
                    {
                        APP_PRINT(MENUEVENT2);
                        result = update_aes_key();
                        if(true==result)
                        {
                            APP_PRINT(RESULT2_SUCCESS);
                        }
                        else
                        {
                            APP_PRINT(RESULT2_FAILURE);
                        }
                        print_main_menu();

                    }
                    break;
                    case DECRYPT_WITH_UPDATED_AES_KEY:
                    {
                        APP_PRINT(MENUEVENT3);
                        result = cipher_operation_with_updated_aes_key();
                        if(true==result)
                        {
                            APP_PRINT(RESULT3_SUCCESS);
                        }
                        else
                        {
                            APP_PRINT(RESULT3_FAILURE);
                        }
                        print_main_menu();
                    }
                    break;
                    case OPERATE_DIRECTLY_INJECTED_ECC_PUB_KEY:
                    {
                        APP_PRINT(MENUEVENT4);
                        result = cryptograhpic_operation_with_directly_injected_ecc_pub_key();
                        if(true==result)
                        {
                            APP_PRINT(RESULT4_SUCCESS);
                        }
                        else
                        {
                            APP_PRINT(RESULT4_FAILURE);
                        }
                        print_main_menu();
                    }
                    break;
                    case UPDATE_ECC_PUB_KEY:
                    {
                        APP_PRINT(MENUEVENT5);
                        result = update_ecc_pub_key();
                        if(true==result)
                        {
                            APP_PRINT(RESULT5_SUCCESS);
                        }
                        else
                        {
                            APP_PRINT(RESULT5_FAILURE);
                        }
                        print_main_menu();

                    }
                    break;
                    case OPERATE_UPDATED_ECC_PUB_KEY:
                    {
                        APP_PRINT(MENUEVENT6);
                        result = cryptographic_operation_with_updated_ecc_pub_key();
                        if(true==result)
                        {
                            APP_PRINT(RESULT6_SUCCESS);
                        }
                        else
                        {
                            APP_PRINT(RESULT6_FAILURE);
                        }
                        print_main_menu();
                    }
                    break;
                    default:
                    {
                        APP_PRINT(RESULT7_FAILURE);
                        /* Menu for User Selection */
                        print_main_menu();
                    }
                    break;
                }
            }
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
