/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "icu_ep.h"

/*******************************************************************************************************************//**
 * @addtogroup icu_ep
 * @{
 **********************************************************************************************************************/

/* Board's user LED */
extern bsp_leds_t g_bsp_leds;
/* Boolean flag to determine switch is pressed or not */
extern volatile bool g_sw_press;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err                    = FSP_SUCCESS;
    bsp_io_level_t led_current_state = (bsp_io_level_t) RESET_VALUE;
    fsp_pack_version_t version       = {RESET_VALUE};

    /* LED type structure */
    bsp_leds_t leds = g_bsp_leds;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the J-link RTT Viewer */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,\
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize External IRQ driver */
    err = icu_init();
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** icu_init function failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Enable External IRQ driver */
    err = icu_enable();
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** icu_enable function failed **\r\n");
        /* Close External IRQ module */
        icu_deinit();
        APP_ERR_TRAP(err);
    }

    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == leds.led_count)
    {
        APP_PRINT("\r\nThere are no LEDs on this board\r\n");
        /* Close External IRQ module */
        icu_deinit();
        APP_ERR_TRAP(err);
    }

    /* Main loop */
    while (true)
    {
        /* Toggle user LED when user push button is pressed */
        if (true == g_sw_press)
        {
            /* Clear user push button flag */
            g_sw_press = false;

            /* Notify that user push button is pressed */
            APP_PRINT("\r\nUser Push button Pressed\r\n");

            /* Read user LED pin */
            err = R_IOPORT_PinRead(&g_ioport_ctrl, (bsp_io_port_pin_t)leds.p_leds[RESET_VALUE], &led_current_state);
            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_IOPORT_PinRead FAILED **\r\n");
                /* Close External IRQ module */
                icu_deinit();
                APP_ERR_TRAP(err);
            }

            /* Reverse LED pin state */
            led_current_state ^= BSP_IO_LEVEL_HIGH;

            /* Toggle user LED */
            err = R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)leds.p_leds[RESET_VALUE], led_current_state);

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("** R_IOPORT_PinWrite FAILED **\r\n");
                /* Close External IRQ module */
                icu_deinit();
                APP_ERR_TRAP(err);
            }

#if defined (BOARD_RA6T1_RSSK) || defined (BOARD_RA4W1_EK) || defined (BOARD_RA4T1_MCK) || defined (BOARD_RA6T2_MCK)\
    || defined (BOARD_RA6T3_MCK) || defined (BOARD_RA8T1_MCK) || defined (BOARD_RA8T2_MCK)
            if (BSP_IO_LEVEL_LOW == led_current_state)
#else
            if (BSP_IO_LEVEL_HIGH == led_current_state)
#endif
            {
                /* Print LED pin state */
                APP_PRINT("LED State: High{ON}\r\n");
            }
            else
            {
                /* Print LED pin state */
                APP_PRINT("LED State: Low{OFF}\r\n");
            }
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build) */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup icu_ep)
 **********************************************************************************************************************/
