/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 **********************************************************************************************************************/

#include "common_utils.h"
#include "sci_i2c_ep.h"

/*******************************************************************************************************************//**
 * @addtogroup sci_i2c_ep
 * @{
 **********************************************************************************************************************/

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t          err     = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);
    APP_PRINT(EP_INFO);

    /* SCI_I2C Master and IIC Slave drivers initialization */
    err = init_i2c_driver();
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* SCI_I2C Master and IIC Slave initialization failed */
        APP_ERR_PRINT("\r\n** IIC driver initialization FAILED **\r\n");

        /* Turn ON LED */
        set_led(LED_ON);
        APP_ERR_TRAP(err);
    }

    while (true)
    {

        /* Performs SCI_I2C write/read operation */
        err = process_master_WriteRead();

        /* Clean up on SCI_I2C Master write/read failure
         * Note: For demonstration purposes, failure results in a trap.
         * Note: This can be handled differently depending on application requirements */

        /* Handle error */
        if (FSP_SUCCESS != err)
        {
            /* Turn on LED */
            set_led(LED_ON);

            /* Print RTT message */
            APP_ERR_PRINT("\r\n** "SCI_TYPE"_I2C Master transaction failed, closing open modules **\r\n");

            /* De-initialize opened SCI_I2C Master and IIC Slave modules */
            deinit_i2c_driver();

            APP_ERR_TRAP(err);
        }

        /* Wait 1 second to recognize LED toggling between successive Write and Read operations */
        R_BSP_SoftwareDelay(DELAY_OPERATION, BSP_DELAY_UNITS_SECONDS);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup sci_i2c_ep)
 **********************************************************************************************************************/
