/***********************************************************************************************************************
 * File Name    : system_thread_entry.c
 * Description  : Contains entry function of system control.
 ***********************************************************************************************************************/
/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
#include "system_thread.h"
#include "guix_gen/Hello_World_resources.h"
#include "guix_gen/Hello_World_specifications.h"

#define APP_ERR_TRAP(err)           if(err) { __asm("BKPT #0\n");} /* trap upon the error  */
#define GUI_MEM_SDRAM_POOL (783360U)


TX_BYTE_POOL g_guix_pool_sdram;
UCHAR g_mem_guix_pool_sdram[GUI_MEM_SDRAM_POOL] BSP_ALIGN_VARIABLE(8) BSP_PLACE_IN_SECTION(".sdram");

/* Root Window and screen pointers */
GX_WINDOW_ROOT* p_root;
GX_WINDOW*      p_window1_screen;
GX_WINDOW*      p_window2_screen;

/***********************************************************************************************************************
 Private functions
 ***********************************************************************************************************************/

static fsp_err_t gpt_timer_PWM_setup(void);

/* System Thread entry function */
void system_thread_entry(void)
{
    fsp_err_t     err            = FSP_SUCCESS;
    UINT          gx_err         = GX_SUCCESS;

    /* Initializes GUIX. */
    gx_err = gx_system_initialize();
    if(TX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Configure main display */
    gx_err = gx_studio_display_configure(DISPLAY,
                                rm_guix_port_hw_initialize,
                                LANGUAGE_ENGLISH,
                                DISPLAY_THEME_1,
                                &p_root);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Set pointer to the first buffer generated by the configuration (rm_guix_port_canvas) */
    gx_err = gx_canvas_memory_define(p_root->gx_window_root_canvas,
                            rm_guix_port_canvas,
                            p_root->gx_window_root_canvas->gx_canvas_memory_size);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Create the widget and attached to root window.*/
    gx_err = gx_studio_named_widget_create("Window1", (GX_WIDGET *) p_root, (GX_WIDGET **) &p_window1_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    gx_err = gx_studio_named_widget_create("Window2", GX_NULL, (GX_WIDGET **) &p_window2_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Shows the root window. */
    gx_err = gx_widget_show(p_root);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Start GUIX */
    gx_err = gx_system_start();
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Set up GPT/PWM timer using for LCD back light control */
    err = gpt_timer_PWM_setup();
    if(FSP_SUCCESS != err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
        tx_thread_sleep (1);
    }


/*******************************************************************************************************************//**
 * @brief This function is setting up GPT/PWM timer
 * @param[in] None
 * @retval    fsp_err_t
 **********************************************************************************************************************/
static fsp_err_t gpt_timer_PWM_setup(void)
{
    fsp_err_t err = FSP_SUCCESS;
    /* Open GPT */
    err = R_GPT_Open(&g_timer_PWM_ctrl, &g_timer_PWM_cfg);
    if(FSP_SUCCESS != err)
    {
        return err;
    }
    /* Enable GPT Timer */
    err = R_GPT_Enable(&g_timer_PWM_ctrl);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        return err;
    }
    /* Start GPT timer */
    err = R_GPT_Start(&g_timer_PWM_ctrl);;
    if(FSP_SUCCESS != err)
    {
        return err;
    }

    return err;
}

