/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "dac_ep.h"

/*******************************************************************************************************************//**
 * @addtogroup dac_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Variable to store the user input for DAC conversion */
static int32_t g_inputRead = RESET_VALUE;
/* Flag to notify that ADC read is complete */
static volatile bool b_is_read_complete = false;
/* Flag to notify any error in reading ADC data */
static volatile bool b_error_flag = false;

/* Variable to store scanned ADC data */
static uint16_t g_adc_data = RESET_VALUE;
#if defined(BOARD_RA2A1_EK) || (BSP_PERIPHERAL_ADC_B_PRESENT)
/* Function for ADC calibration on RA2A1 board and ADC_B version */
static fsp_err_t adc_start_calibration(void);
/* Flag to notify successful calibration completion */
static volatile bool b_is_calibration_complete = false;
#endif
/* Function to process the user input */
static fsp_err_t read_process_input_from_RTT(void);
/* Function to process the user input for DAC conversion */
static fsp_err_t dac_adc_operations(int32_t * input);

/* Functions to close opened modules */
static void dac_deinit(void);
static void adc_deinit(void);

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = { RESET_VALUE };

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);
    APP_PRINT(EP_INFO);

    /* Configure DAC12 output pin for EK-RA2A1 */
#if defined(BOARD_RA2A1_EK)
    err = R_IOPORT_PinCfg(&g_ioport_ctrl, DAC12_OUTPUT_PIN, IOPORT_CFG_ANALOG_ENABLE |\
                          IOPORT_CFG_PERIPHERAL_PIN | IOPORT_PERIPHERAL_CAC_AD);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n** R_IOPORT_PinCfg API failed **\r\n");
        APP_ERR_TRAP(err);
    }
#endif

    /* Open the DAC channel */
#if (BSP_PERIPHERAL_DAC_B_PRESENT)
    err = R_DAC_B_Open(&g_dac_b_ctrl, &g_dac_b_cfg);
#else
    err = R_DAC_Open(&g_dac_ctrl, &g_dac_cfg);
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DAC module open failed */
        APP_ERR_PRINT("\r\n** R_"DAC_TYPE"_Open API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Open/Initialize ADC module */
 #if (BSP_PERIPHERAL_ADC_B_PRESENT)
    err = R_ADC_B_Open(&g_adc_ctrl, &g_adc_cfg);
 #else
    err = R_ADC_Open(&g_adc_ctrl, &g_adc_cfg);
 #endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
     /* ADC module open failed */
     dac_deinit();
     /* ADC failure message */
     APP_ERR_PRINT("\r\n** R_"ADC_TYPE"_Open API failed **\r\n");
     APP_ERR_TRAP(err);
    }

    /* Configures the ADC scan parameters */
#if (BSP_PERIPHERAL_ADC_B_PRESENT)
    err = R_ADC_B_ScanCfg(&g_adc_ctrl, &g_adc_scan_cfg);
#else
    err = R_ADC_ScanCfg(&g_adc_ctrl, &g_adc_channel_cfg);
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        adc_deinit();
        dac_deinit();
        /* ADC failure message */
        APP_ERR_PRINT("\r\n** R_"ADC_TYPE"_ScanCfg API failed **\r\n");
        APP_ERR_TRAP(err);
    }

#if defined(BOARD_RA2A1_EK) || (BSP_PERIPHERAL_ADC_B_PRESENT)
    /* Set Reference Voltage Circuit Control register */
#if !defined(BOARD_RA8P1_EK)
    R_ADC0->VREFAMPCNT |= ((VREFADCG_VALUE) | (VREFADCG_ENABLE));
#endif

    /* Calibrate the ADC */
    err = adc_start_calibration();
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        adc_deinit();
        dac_deinit();
        /* ADC failure message */
        APP_ERR_PRINT("\r\n** adc_start_calibration failed **\r\n");
        APP_ERR_TRAP(err);
    }
#endif

    APP_PRINT("\r\nEnter values for DAC conversion. Input Range: 1 to 4095\r\n");

    while (true)
    {
        if (APP_CHECK_DATA)
        {
            /* Validate input value from the user */
            err = read_process_input_from_RTT ();
            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                /* Notify the user if the input is not valid */
                APP_PRINT("\r\nInvalid Input. Valid Range: 1 to 4095. Please enter valid input.\r\n");
            }
            /* Process valid input from the user */
            else
            {
                err = dac_adc_operations(&g_inputRead);
                /* Handle error */
                if (FSP_SUCCESS != err)
                {
                    adc_deinit();
                    dac_deinit();
                    APP_ERR_PRINT("\r\n** Processing input failed **\r\n");
                    APP_ERR_TRAP(err);
                }
            }
        }

        /* Print read ADC output data */
        if (true == b_is_read_complete)
        {
            b_is_read_complete = false;
            APP_PRINT("\r\nData read from ADC channel: %d\r\n", g_adc_data);

#if defined(BOARD_RA4W1_EK) || defined(BOARD_RA6T1_RSSK)
            adc_deinit();
#endif
        }
        else if (true == b_error_flag)
        {
            adc_deinit();
            dac_deinit();
            /* ADC failure message */
            APP_ERR_PRINT("\r\n** R_"ADC_TYPE"_Read failed **\r\n");
            APP_ERR_TRAP(err);
        }
        else
        {
            /* Do nothing */
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * @brief       This function reads the user input from RTT and processes it.
 * @param[IN]   None
 * @retval      FSP_SUCCESS     Upon successful of conversion of the user input value.
 * @retval      Any other error code apart from FSP_SUCCESS     Unsuccessful DAC conversion.
 **********************************************************************************************************************/
static fsp_err_t read_process_input_from_RTT(void)
{
    fsp_err_t err = FSP_SUCCESS;

    uint8_t readBuff[BUFFER_SIZE_DOWN] = { RESET_VALUE };

    /* Read input value for DAC conversion from the user */
    APP_READ(readBuff);

    /* Convert the input string to an integer value */
    g_inputRead = atoi ((char *) readBuff);

    if ((DAC_MIN_VAL <= g_inputRead) && (DAC_MAX_VAL >= g_inputRead))
    {
        APP_PRINT("\r\nUser input value for DAC conversion : %d\r\n", g_inputRead);
    }
    else
    {
        err = FSP_ERR_INVALID_ARGUMENT;
    }

    return err;
}

#if defined(BOARD_RA2A1_EK) || (BSP_PERIPHERAL_ADC_B_PRESENT)
/*******************************************************************************************************************//**
 * @brief       This function initiates the ADC calibration
 * @param[IN]   None
 * @retval      FSP_SUCCESS     Upon successful of ADC calibration
 * @retval      Any Other Error code apart from FSP_SUCCESS  Unsuccessful calibration failure
 **********************************************************************************************************************/
static fsp_err_t adc_start_calibration(void)
{
    fsp_err_t err = FSP_SUCCESS;     /* Error status */

    APP_PRINT("\r\nADC Calibration Started\r\n");

    /* Initiate ADC calibration */
#if (BSP_PERIPHERAL_ADC_B_PRESENT)
    err = R_ADC_B_Calibrate(&g_adc_ctrl, NULL);
#else
    err = R_ADC_Calibrate(&g_adc_ctrl, NULL);
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n** R_"ADC_TYPE"_Calibrate API failed **\r\n");
        return err;
    }
    /* Wait here till the calibration is complete. It takes 24msec to 780msec based on clock */
    while (!b_is_calibration_complete); 

    APP_PRINT("\r\nADC Calibration Successful\r\n");

    return err;
}
#endif

/*******************************************************************************************************************//**
 * @brief       This function performs DAC conversion and ADC Scan operation
 * @param[IN]   input           The user input for DAC conversion
 * @retval      FSP_SUCCESS     Upon successful of ADC calibration
 * @retval      Any Other Error code apart from FSP_SUCCESS  Unsuccessful DAC conversion or ADC scan
 **********************************************************************************************************************/
static fsp_err_t dac_adc_operations(int32_t * input)
{
    fsp_err_t err = FSP_SUCCESS;     /* Error status */

    /* Write value to DAC module */
#if (BSP_PERIPHERAL_DAC_B_PRESENT)
    err = R_DAC_B_Write(&g_dac_b_ctrl, (uint16_t)(* input));
#else
    err = R_DAC_Write(&g_dac_ctrl, (uint16_t)(* input));
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DAC Write Failure message */
        APP_ERR_PRINT("\r\n** R_"DAC_TYPE"_Write API failed **\r\n");
        return err;
    }

    /* Start DAC conversion */
#if (BSP_PERIPHERAL_DAC_B_PRESENT)
    err = R_DAC_B_Start(&g_dac_b_ctrl);
#else
    err = R_DAC_Start(&g_dac_ctrl);
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DAC start failure message */
        APP_ERR_PRINT("\r\n** R_"DAC_TYPE"_Start API failed **\r\n");
        return err;
    }

    /* As per mention in section 35.3.1 of EK-RA4W1 hardware user manual, DAC can't be synchronized with ADC
     * because both are sharing the same bus */
#if defined(BOARD_RA4W1_EK) || defined( BOARD_RA6T1_RSSK)
    /* Open/Initialize ADC module */
    err = R_ADC_Open(&g_adc_ctrl, &g_adc_cfg);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* ADC module open failed */
        dac_deinit();
        APP_ERR_PRINT("\r\n** R_ADC_Open API failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Configures the ADC scan parameters */
    err = R_ADC_ScanCfg(&g_adc_ctrl, &g_adc_channel_cfg);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        adc_deinit();
        dac_deinit();
        /* ADC Failure message */
        APP_ERR_PRINT("\r\n** R_ADC_ScanCfg API failed **\r\n");
        APP_ERR_TRAP(err);
    }
#endif

    /* As mentioned in DAC properties and Electrical characteristics of RA8E2 User Manual (Section 51.6),
     * a software delay has to be given for stabilizing the voltage on DAC output pin.
     * Also referred as DAC conversion time delay */
    R_BSP_SoftwareDelay(STABILIZATION_DELAY, BSP_DELAY_UNITS_MILLISECONDS);

/*     Start the ADC scan in Single scan mode */
#if (BSP_PERIPHERAL_ADC_B_PRESENT)
        err = R_ADC_B_ScanGroupStart(&g_adc_ctrl, ADC_GROUP_MASK_0);
#else
        err = R_ADC_ScanStart(&g_adc_ctrl);
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* ADC failure message */
        APP_ERR_PRINT("\r\n** R_"ADC_TYPE"_ScanStart API failed **\r\n");
        return err;
    }

    /* Stop DAC conversion for consecutive the user input values */
#if (BSP_PERIPHERAL_DAC_B_PRESENT)
    err = R_DAC_B_Stop(&g_dac_b_ctrl);
#else
    err = R_DAC_Stop(&g_dac_ctrl);
#endif
    /* Handle Error */
    if (FSP_SUCCESS != err)
    {
        /* DAC stop failure message */
        APP_ERR_PRINT("\r\n** R_"DAC_TYPE"_Stop API failed **\r\n");
    }
    return err;
}

/*******************************************************************************************************************//**
 * @brief       ADC callback function.
 * @param[in]   p_args
 * @retval      None
 **********************************************************************************************************************/
void g_adc_callback(adc_callback_args_t *p_args)
{
    if (ADC_EVENT_SCAN_COMPLETE == p_args->event)
    {
        fsp_err_t err = FSP_SUCCESS;     /* Error status */

        /* Read the result after ADC Scan is complete */
#if (BSP_PERIPHERAL_ADC_B_PRESENT)
        err = R_ADC_B_Read(&g_adc_ctrl, ADC_CHANNEL, &g_adc_data);
#else
        err = R_ADC_Read(&g_adc_ctrl, ADC_CHANNEL, &g_adc_data);
#endif
        /* Handle error */
        if (FSP_SUCCESS != err)
        {
            b_error_flag = true;
        }
        else
        {
            b_is_read_complete = true;
        }
    }

#if defined(BOARD_RA2A1_EK) || (BSP_PERIPHERAL_ADC_B_PRESENT)

    /* Check if calibration is complete and set flag */
    else if (ADC_EVENT_CALIBRATION_COMPLETE == p_args->event)
    {
        b_is_calibration_complete = true;
    }
    else
    {
        /* Do nothing */
    }
#endif
}

/*******************************************************************************************************************//**
 * @brief       This function closes opened DAC module before the project ends up in an error trap.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void dac_deinit(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Close DAC module */
#if (BSP_PERIPHERAL_DAC_B_PRESENT)
    err = R_DAC_B_Close(&g_dac_b_ctrl);
#else
    err = R_DAC_Close(&g_dac_ctrl);
#endif
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        /* DAC Close failure message */
        APP_ERR_PRINT("\r\n** R_"DAC_TYPE"_Close API failed **\r\n");
    }
}

/*******************************************************************************************************************//**
 * @brief       This function closes opened ADC module before the project ends up in an error trap.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void adc_deinit(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Close ADC module */
#if (BSP_PERIPHERAL_ADC_B_PRESENT)
        err = R_ADC_B_Close(&g_adc_ctrl);
#else
        err = R_ADC_Close(&g_adc_ctrl);
#endif
    /* Handle error */
   if (FSP_SUCCESS != err)
   {
       /* ADC failure message */
       APP_ERR_PRINT("\r\n** R_"ADC_TYPE"_Close API failed **\r\n");
   }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take
         * more than 6us */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

        /* Configure pins */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build) */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup dac_ep)
 **********************************************************************************************************************/
