/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
 * SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2022 Renesas Electronics Corporation. All rights reserved.
 ***********************************************************************************************************************/
#include "drw_ep.h"
#include "hal_data.h"
#include "common_utils.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* DRW Variables */
static d2_device * gp_davey;
static d2_s32             DRW_err;

/* Variables for different figures */
/* Circle variables */
static d2_point g_c_c_x1 = CIRCLE_VAL_X, g_c_c_y1 = CIRCLE_VAL_Y, g_c_r = CIRCLE_VAL_R, g_c_w = CIRCLE_VAL_W;
static bool g_c_left_flag = true, g_c_right_flag = false;
/* Triangle variables */
static d2_point g_t_x1 = TRIANGLE_X1, g_t_y1 = TRIANGLE_Y1, g_t_x2 = TRIANGLE_X2, g_t_y2 = TRIANGLE_Y2, g_t_x3 = TRIANGLE_X3, g_t_y3 = TRIANGLE_Y3;
static bool g_t_top_flag = true, g_t_bottom_flag = false;
/* Box variables */
static d2_point g_b_x1 = BOX_VAL_X1, g_b_y1 = BOX_VAL_Y1, g_b_l = BOX_VAL_LEN, g_b_w = BOX_VAL_WIDTH;
static bool g_p_top_flag = false, g_p_bottom_flag = true;
/* line variables */
static d2_point g_l_x1 = LINE_VAL_X1, g_l_y1 = LINE_VAL_Y1, g_l_x2 = LINE_VAL_X2, g_l_y2 = LINE_VAL_Y2, g_l_w = LINE_VAL_WIDTH;
static bool g_l_left_flag = false, g_l_right_flag = true;

/* GLCDC Variables */
/* Variables to store resolution information */
static uint16_t g_hz_size = RESET_VALUE;
static uint16_t g_vr_size = RESET_VALUE;
/* Variables used for buffer usage */
static uint32_t g_buffer_size = RESET_VALUE;
static uint8_t * g_p_single_buffer, * g_p_double_buffer;
volatile uint8_t g_vsync_flag = RESET_FLAG;

/* User defined functions */
void glcdc_callback(display_callback_args_t * args);
static void drw_set(uint8_t * framebuffer);
static void drw_animation(void);
static void display_draw(uint8_t * framebuffer);
static void error_handler(d2_s32 DRW_err,d2_device * gp_davey);
static void glcdc_init(void);
static void drw_init(void);


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version    = {RESET_VALUE};
    uint8_t * p_framebuffer = NULL;

    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Get LCDC configuration */
    g_hz_size = (g_display_cfg.input[ARRAY_INDEX].hsize);
    g_vr_size = (g_display_cfg.input[ARRAY_INDEX].vsize);
    /* Initialize buffer pointers */
    g_buffer_size = (uint32_t) (g_hz_size * g_vr_size * BYTES_PER_PIXEL);
    g_p_single_buffer = (uint8_t *) g_display_cfg.input[ARRAY_INDEX].p_base;
    /* Double buffer for drawing color bands with good quality */
    g_p_double_buffer = g_p_single_buffer + g_buffer_size;

    /* GLCDC init */
    glcdc_init();

    /* Wait for a Vsync event */
    while(!g_vsync_flag);
    g_vsync_flag = RESET_FLAG;

    /* DRW initialization */
    drw_init();

    while(true)
    {
        /* Swap the active framebuffer */
        p_framebuffer = (p_framebuffer == g_p_single_buffer) ? g_p_double_buffer : g_p_single_buffer;

        /* Wait for a Vsync event */
        while(!g_vsync_flag);
        g_vsync_flag = RESET_FLAG;

        /* Now that the framebuffer is ready, update the GLCDC buffer pointer on the next Vsync */
        err = R_GLCDC_BufferChange(&g_display_ctrl, p_framebuffer, DISPLAY_FRAME_LAYER_1);
        /* Handle error */
        if(FSP_SUCCESS != err)
        {
            /* GLCDC initialization failed  */
            APP_ERR_PRINT("\r\n ** GLCDC Buffer change FAILED ** \r\n");
            APP_ERR_TRAP(err);
        }

        /* Draw the new framebuffer now */
        display_draw(p_framebuffer);
    }

    APP_PRINT("\r\n ** Image rendering successful ** \r\n");

    /* Wait for rendering operations to finish */
    DRW_err = d2_flushframe(gp_davey);
    error_handler(DRW_err, gp_davey);

    /* De-initialize hardware and close the handle */
    DRW_err = d2_deinithw(gp_davey);
    error_handler(DRW_err, gp_davey);

    DRW_err = d2_closedevice(gp_davey);
    error_handler(DRW_err, gp_davey);

    /* Stop GLCDC */
    err = R_GLCDC_Stop(&g_display_ctrl);
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        /* GLCDC initialization failed  */
        APP_ERR_PRINT("\r\n ** GLCDC driver stop FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n ** GLCDC driver stopped ** \r\n");
    }

    /* Close GLCDC */
    err = R_GLCDC_Close(&g_display_ctrl);
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        /* GLCDC initialization failed  */
        APP_ERR_PRINT("\r\n ** GLCDC driver close FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n ** GLCDC driver closed ** \r\n");
    }



#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

/*******************************************************************************************************************//**
 * User defined function to initialize glcdc module
 *
 * @param      none
 * @retval     none
 **********************************************************************************************************************/
static void glcdc_init(void)
{
    fsp_err_t err = FSP_SUCCESS;
    /* Initialize GLCDC driver */
    err = R_GLCDC_Open(&g_display_ctrl, &g_display_cfg);
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        /* GLCDC initialization failed  */
        APP_ERR_PRINT("\r\n ** GLCDC driver initialization FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n ** GLCDC driver initialization SUCCESS ** \r\n");
    }

    /* Start GLCDC display output */
    err = R_GLCDC_Start(&g_display_ctrl);
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        /* GLCDC initialization failed  */
        APP_ERR_PRINT("\r\n ** GLCDC driver start FAILED ** \r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n ** GLCDC driver start SUCCESS ** \r\n");
    }
}

/*******************************************************************************************************************//**
 * User defined function to initialize drw module
 *
 * @param      none
 * @retval     none
 **********************************************************************************************************************/
static void drw_init(void)
{
    /* Open the D2 driver and initialize the hardware */
    gp_davey = d2_opendevice(BITFIELD_VALUE);
    DRW_err = d2_inithw(gp_davey, BITFIELD_VALUE);
    if (D2_OK == DRW_err)
    {
        APP_PRINT("\r\n ** DRW driver initialization SUCCESS ** \r\n");
    }
    else
    {
        error_handler(DRW_err, gp_davey);
    }

    /* set the transparency and the alpha mode */
    DRW_err = d2_setalpha(gp_davey, ALPHA_VALUE);
    if (D2_OK == DRW_err)
    {
        APP_PRINT("\r\n ** Transparency set successfully ** \r\n");
    }
    else
    {
        error_handler(DRW_err, gp_davey);
    }

    DRW_err = d2_setalphamode(gp_davey, d2_am_constant);
    if (D2_OK == DRW_err)
    {
        APP_PRINT("\r\n ** Alphamode set successfully ** \r\n");
    }
    else
    {
        error_handler(DRW_err, gp_davey);
    }

    /* Set alphablend mode */
    DRW_err = d2_setblendmode(gp_davey, d2_bm_alpha, d2_bm_one_minus_alpha);
    if (D2_OK == DRW_err)
    {
        APP_PRINT("\r\n ** Alphablend mode set succesfully ** \r\n");
    }
    else
    {
        error_handler(DRW_err, gp_davey);
    }
}

/*******************************************************************************************************************//**
 * Error handler for DRW.
 *
 * @param[in]  err       Error returned from DRW APIs
 * @param[in]  gp_dave   Pointer to device structure
 * @retval     none
 **********************************************************************************************************************/
static void error_handler(d2_s32 err, d2_device * gp_dave)
{
    if (D2_OK != err)
    {
        /* print the error message */
        APP_ERR_PRINT(d2_geterrorstring( gp_dave ));
        APP_ERR_TRAP(err);
    }
}

/*******************************************************************************************************************//**
 * Callback functions for GLCDC interrupts
 *
 * @param[in]  p_args    Callback arguments
 * @retval     none
 **********************************************************************************************************************/
void glcdc_callback (display_callback_args_t * p_args)
{
    if (p_args->event == DISPLAY_EVENT_LINE_DETECTION)
    {
        g_vsync_flag = SET_FLAG;
    }
}

/*******************************************************************************************************************//**
 * User-defined function to draw the current display to a framebuffer
 *
 * @param[in]  framebuffer    Pointer to frame buffer
 * @retval     none
 **********************************************************************************************************************/
static void display_draw (uint8_t * framebuffer)
{
    /* DRW operations happens here */
    /*Animation of different figures */
    drw_animation();

    /* set frame buffer properties */
    drw_set(framebuffer);

    /* Set the render color to red */
    DRW_err = d2_setcolor(gp_davey, ARRAY_INDEX, RED_COLOR_VAL);
    error_handler(DRW_err, gp_davey);

    /* Render a circle */
    DRW_err = d2_rendercircle(gp_davey,(d2_point)(g_c_c_x1 << SHIFT_VALUE), (d2_point)(g_c_c_y1 << SHIFT_VALUE), (d2_width)(g_c_r << SHIFT_VALUE), (d2_width)(g_c_w << SHIFT_VALUE));
    error_handler(DRW_err, gp_davey);

    /* Set the render color to green */
    DRW_err = d2_setcolor(gp_davey, ARRAY_INDEX, GREEN_COLOR_VAL);
    error_handler(DRW_err, gp_davey);

    /* Render a triangle */
    DRW_err = d2_rendertri(gp_davey, (d2_point)( g_t_x1 << SHIFT_VALUE),(d2_point)( g_t_y1 << SHIFT_VALUE),(d2_point)( g_t_x2 << SHIFT_VALUE),(d2_point)( g_t_y2 << SHIFT_VALUE),(d2_point)( g_t_x3 << SHIFT_VALUE),(d2_point)( g_t_y3 << SHIFT_VALUE),d2_edge2_shared);
    error_handler(DRW_err, gp_davey);

    /* Set the render color to blue */
    DRW_err = d2_setcolor(gp_davey, ARRAY_INDEX, BLUE_COLOR_VAL);
    error_handler(DRW_err, gp_davey);

    /* Render a box */
    DRW_err = d2_renderbox(gp_davey,(d2_point)(g_b_x1 << SHIFT_VALUE), (d2_point)(g_b_y1 << SHIFT_VALUE), (d2_width)(g_b_l << SHIFT_VALUE), (d2_width)(g_b_w << SHIFT_VALUE));
    error_handler(DRW_err, gp_davey);

    /* Set the render color to yellow */
    DRW_err = d2_setcolor(gp_davey, ARRAY_INDEX, YELLOW_COLOR_VAL);
    error_handler(DRW_err, gp_davey);

    /* Render a line */
    DRW_err = d2_renderline(gp_davey, (d2_point) (g_l_x1 << SHIFT_VALUE), (d2_point) (g_l_y1 << SHIFT_VALUE), (d2_point) (g_l_x2 << SHIFT_VALUE), (d2_point) (g_l_y2 << SHIFT_VALUE),
                            (d2_width) (g_l_w << SHIFT_VALUE), d2_le_exclude_both);
    error_handler(DRW_err, gp_davey);

    /* End the display list, then call d2_startframe to begin execution */
    DRW_err = d2_endframe(gp_davey);
    error_handler(DRW_err, gp_davey);
}

/*******************************************************************************************************************//**
 * User-defined function to set framebuffer properties
 *
 * @param[in]  framebuffer    Pointer to frame buffer
 * @retval     none
 **********************************************************************************************************************/
static void drw_set(uint8_t * framebuffer)
{
    /* Start a frame */
    DRW_err = d2_startframe(gp_davey);
    error_handler(DRW_err, gp_davey);

    /* Set the frame buffer */
    DRW_err = d2_framebuffer(gp_davey, framebuffer, DRW_TEST_IMAGE_RES_H, DRW_TEST_IMAGE_RES_H, DRW_TEST_IMAGE_RES_V, d2_mode_rgb565);
    error_handler(DRW_err, gp_davey);

    /* Clear the frame buffer */
    DRW_err = d2_clear(gp_davey, BUFFER_CLEAR_VAL);
    error_handler(DRW_err, gp_davey);

    /* Set anti-aliasing and line cap settings */
    DRW_err = d2_setantialiasing(gp_davey, ANTI_ALIASING_VAL);
    error_handler(DRW_err, gp_davey);

    DRW_err = d2_setlinecap(gp_davey, d2_lc_round);
    error_handler(DRW_err, gp_davey);

    DRW_err = d2_setlinejoin(gp_davey, d2_lj_none);
    error_handler(DRW_err, gp_davey);

    /* Set render mode */
    DRW_err = d2_selectrendermode(gp_davey , d2_rm_solid);
    error_handler(DRW_err, gp_davey);
}

/*******************************************************************************************************************//**
 * User defined function to handle animation of different figures
 *
 * @param      none
 * @retval     none
 **********************************************************************************************************************/
static void drw_animation(void)
{
    /* circle animation */
    if((g_c_c_x1 < TRIANGLE_X2) && (g_c_left_flag == true))
    {
        g_c_c_x1++;
    }
    if(g_c_c_x1 >= TRIANGLE_X2)
    {
        g_c_right_flag = true;
        g_c_left_flag = false;
    }

    if((g_c_c_x1 > CIRCLE_VAL_X) && (g_c_right_flag == true))
    {
        g_c_c_x1--;
    }
    if(g_c_c_x1 <= CIRCLE_VAL_X)
    {
        g_c_left_flag = true;
        g_c_right_flag = false;
    }

    /* line animation */
    if((g_l_x1 > BOX_VAL_X1) && (g_l_right_flag == true))
    {
        g_l_x1--;
        g_l_x2--;
    }
    if(g_l_x1 <= BOX_VAL_X1)
    {
        g_l_left_flag = true;
        g_l_right_flag = false;
    }

    if((g_l_x1 < LINE_VAL_X1) && (g_l_left_flag == true))
    {
        g_l_x1++;
        g_l_x2++;
    }
    if(g_l_x1 >= LINE_VAL_X1)
    {
        g_l_right_flag = true;
        g_l_left_flag = false;
    }

    /* triangle animation */
    if((g_t_y1 < LINE_VAL_Y1) && (g_t_top_flag == true))
    {
        g_t_y1++;
        g_t_y2++;
        g_t_y3++;
    }
    if(g_t_y1 >= LINE_VAL_Y1)
    {
        g_t_top_flag = false;
        g_t_bottom_flag = true;
    }

    if((g_t_y1 > TRIANGLE_Y1) && (g_t_bottom_flag == true))
    {
        g_t_y1--;
        g_t_y2--;
        g_t_y3--;
    }
    if(g_t_y1 <= TRIANGLE_Y1)
    {
        g_t_top_flag = true;
        g_t_bottom_flag = false;
    }

    /* Polygon animation */
    if((g_b_y1 > BOX_PARAM) && (g_p_bottom_flag == true))
    {
        g_b_y1--;
    }
    if(g_b_y1 <= BOX_PARAM)
    {
        g_p_top_flag = true;
        g_p_bottom_flag = false;
    }

    if((g_b_y1 < BOX_VAL_Y1) && (g_p_top_flag == true))
    {
        g_b_y1++;
    }
    if(g_l_x1 >= BOX_VAL_Y1)
    {
        g_p_bottom_flag = true;
        g_p_top_flag = false;
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
