/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "ceu.h"

/* External variables */
extern uint32_t g_image_width;
extern uint32_t g_image_height;
extern uint8_t * gp_image_buffer;
extern sensor_reg_t const * gp_cam_resolution;
extern capture_instance_t const * gp_ceu_instance;

volatile bool g_camera_capture_complete_flag = false;

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t          err     = FSP_SUCCESS;

    /* Version get API for FSP pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the RTT */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT_WAIT;
    APP_PRINT(EP_INFO);
    APP_PRINT_WAIT;

    R_BSP_SoftwareDelay(20, BSP_DELAY_UNITS_MICROSECONDS);

    /* Release reset pin */
    R_IOPORT_PinWrite(&g_ioport_ctrl, PIN_CAM_RESET, BSP_IO_LEVEL_HIGH);

    /* Initialize GPT module */
    err = R_GPT_Open(&g_timer_periodic_ctrl, &g_timer_periodic_cfg);
    handle_error(err, "** R_GPT_Open API FAILED **\r\n");

    /* Start GPT module to provide the 24MHz clock frequency output for the camera clock source */
    err = R_GPT_Start(&g_timer_periodic_ctrl);
    handle_error(err, "** R_GPT_Start API FAILED **\r\n");

    R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MILLISECONDS);

    /* Initialize IIC module */
    err = R_IIC_MASTER_Open(&g_i2c_master_for_cam_ctrl, &g_i2c_master_for_cam_cfg);
    handle_error(err, "** R_IIC_MASTER_Open API FAILED **\r\n");

    /* Initialize camera sensor with output format as YUV422 */
    err = camera_open();
    handle_error(err, "** camera_open FAILED **\r\n");

    /* Main loop */
    while (true)
    {
        /* User selects type of memory to store image and resolution of image */
        selection_menu();

        /* Set camera resolution specified by camera array pointer */
        err = camera_set_resolution(gp_cam_resolution);
        handle_error(err, "** camera_set_resolution FAILED **\r\n");

        /* Perform CEU operation specified by CEU instance pointer and store image in buffer
         * specified by image buffer pointer */
        err = ceu_operation(gp_ceu_instance, gp_image_buffer, g_image_width, g_image_height);
        handle_error(err, "** ceu_operation FAILED **\r\n");
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while (FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
