/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "can_fd_ep.h"

/* Timeout value */
volatile uint32_t g_time_out = WAIT_TIME;
extern bsp_leds_t g_bsp_leds;

/* User defined function */
static void led_pin_initialisation(void);

/* Flags to be set in callback function */
bool g_canfd_tx_complete = false;
bool g_canfd_rx_complete = false;
bool g_canfd_err_status = false;

/* Acceptance filter array parameters */
const canfd_afl_entry_t p_canfd0_afl[CANFD_CFG_AFL_CH0_RULE_NUM] =
{
    { /* Accept all messages with Extended ID 0x1000-0x1FFF */
        .id =
        {
        /* Specify the ID, ID type and frame type to accept */
        .id         = CANFD_FILTER_ID,
        .frame_type = CAN_FRAME_TYPE_DATA,
        .id_mode    = CAN_ID_MODE_EXTENDED
        },

        .mask =
        {
        /* These values mask which ID/mode bits to compare when filtering messages */
        .mask_id         = MASK_ID,
        .mask_frame_type = ZERO,
        .mask_id_mode    = MASK_ID_MODE
        },

        .destination =
        {
        /* If DLC checking is enabled any messages shorter than the below setting will be rejected */
        .minimum_dlc = (canfd_minimum_dlc_t)ZERO,

        /* Optionally specify a Receive Message Buffer (RX MB) to store accepted frames. RX MBs do not have an
         * interrupt or overwrite protection and must be checked with R_CANFD_InfoGet and R_CANFD_Read */
        .rx_buffer   = CANFD_RX_MB_0,

        /* Specify which FIFO(s) to send filtered messages to. Multiple FIFOs can be OR'd together */
        .fifo_select_flags = CANFD_RX_FIFO_0,
        }
    },
};

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    char rtt_input_buf[BUFFER_SIZE_DOWN] = {NULL_CHAR};

    /* Initialization of LED pins */
    led_pin_initialisation();

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,\
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize CAN FD module */
    err = R_CANFD_Open(&g_canfd0_ctrl, &g_canfd0_cfg);
    /* Error trap */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\nR_CANFD_Open API failed");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\r\nPlease enter any key on RTT Viewer to initiate CAN transmission\r\n");

    while (1)
    {
        /* Check for the user input */
        if (APP_CHECK_DATA)
        {
            APP_READ(rtt_input_buf);
            /* Update transmit frame and initiate CAN transmission */
            canfd_operation();
        }

        /* Check status of transmitted frame and read received data */
        can_read_operation();
        if (true == g_canfd_err_status)
        {
            g_canfd_err_status = false;
            led_update(LED_CASE_3);
            APP_ERR_PRINT("\r\nCAN error detected");
            APP_ERR_TRAP(true);
        }

        /* Re-initialize timeout value */
        g_time_out = WAIT_TIME;
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * @brief       This function initializes state of LED pins.
 * @param[in]   None
 * @return      None
 **********************************************************************************************************************/
static void led_pin_initialisation(void)
{
    if (g_bsp_leds.led_count == 2)
    {
        /* Set the LED pin state ON */
        /* LED 1 */
        R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[0], (bsp_io_level_t) LED_ON);
        /* LED 2 */
        R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[1], (bsp_io_level_t) LED_ON);

        R_BSP_SoftwareDelay(WAIT_TIME, BSP_DELAY_UNITS_MICROSECONDS);

        /* Set the LED pin state OFF */
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[0], (bsp_io_level_t) LED_OFF);
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[1], (bsp_io_level_t) LED_OFF);
    }
    else if (g_bsp_leds.led_count >= 3)
    {
        /* Set the LED pin state ON */
        /* LED 1 */
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[0], (bsp_io_level_t) LED_ON);
        /* LED 2 */
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[1], (bsp_io_level_t) LED_ON);
        /* LED 3 */
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[2], (bsp_io_level_t) LED_ON);

        R_BSP_SoftwareDelay (WAIT_TIME, BSP_DELAY_UNITS_MICROSECONDS);

        /* Set the LED pin state OFF */
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[0], (bsp_io_level_t) LED_OFF);
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[1], (bsp_io_level_t) LED_OFF);
        R_IOPORT_PinWrite (&g_ioport_ctrl, (bsp_io_port_pin_t) g_bsp_leds.p_leds[2], (bsp_io_level_t) LED_OFF);
    }
    else
    {
        /* Do nothing */
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build) */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
