/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "adc_periodic_scan.h"
#include "dtc_hal.h"
#include "adc_hal.h"
#include "gpt_hal.h"
#include "elc_hal.h"

/*******************************************************************************************************************//**
 * @addtogroup adc_gpt_periodic_sampling_ep
 * @{
 **********************************************************************************************************************/

/* Private function declarations */
static void general_signal_acquisition_init(void);
static void handle_error(fsp_err_t err, char *err_str, module_name_t module);

/* Extern variable */
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
extern uint16_t g_buffer_adc[ADC_UNIT_NUM][ADC_GROUP_SCAN_NUM][NUM_ADC_CHANNELS]\
                            [NUM_SAMPLE_BUFFER][NUM_SAMPLES_PER_CHANNEL];
#else
extern uint16_t g_buffer_adc[ADC_UNIT_1][ADC_GROUP_SCAN_NUM][NUM_ADC_CHANNELS]\
                            [NUM_SAMPLE_BUFFER][NUM_SAMPLES_PER_CHANNEL];
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */
extern transfer_info_t g_transfer_adc_group_a[];
extern transfer_info_t g_transfer_adc_group_b[];
extern volatile bool g_adc0_group_a_flag;
extern volatile bool g_adc0_group_b_flag;

#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
extern volatile bool g_adc1_group_a_flag;
extern volatile bool g_adc1_group_b_flag;
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */

#if (BSP_PERIPHERAL_ADC_B_PRESENT)
extern volatile bool g_err_flag_adc_b;
#elif (BSP_PERIPHERAL_ADC_PRESENT)
extern volatile bool g_err_flag_adc0;
#if (BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK)
extern volatile bool g_err_flag_adc1;
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */
#endif /* BSP_PERIPHERAL_ADC_B_PRESENT */

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t          err     = FSP_SUCCESS;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the RTT */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Initialize the HAL drivers used for signal acquisition */
    general_signal_acquisition_init();

    APP_PRINT("\r\nADC periodic scan started...\r\n");

    /* Start ADC Unit 0 */
    err = scan_start_adc(&g_adc0_ctrl);
    handle_error(err, "\r\n** scan_start_adc for unit 0 failed **\r\n", ALL);

#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK
    /* Start ADC Unit 1 */
    err = scan_start_adc(&g_adc1_ctrl);
    handle_error(err, "\r\n** scan_start_adc for unit 1 failed **\r\n", ALL);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */

    /* Start GPT timer */
    err = gpt_timer_start(&g_timer0_ctrl);
    handle_error(err, "\r\n** gpt_timer_start failed **\r\n", ALL);

    APP_PRINT("\r\nThe user can now open waveform rendering of memory in e2studio to observe the output "
              "of ADC GPT periodic sampling.\n\n");

    /* Wait for callback event */
    while (true)
    {
        /* Check if ADC 0 scan complete event for group A is received */
        if (true == g_adc0_group_a_flag)
        {
            /* Buffer select for ping-pong buffer */
            static uint8_t buffer_select = ZERO;
            buffer_select = (buffer_select == ZERO) ? ONE : ZERO;

            /* Update destination address and length for transfer */
            g_transfer_adc_group_a[ZERO].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_0][ADC_GROUP_SCAN_A][ZERO][buffer_select][ZERO];
            g_transfer_adc_group_a[ONE].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_0][ADC_GROUP_SCAN_A][ONE][buffer_select][ZERO];
            g_transfer_adc_group_a[ZERO].length = NUM_SAMPLES_PER_CHANNEL;
            g_transfer_adc_group_a[ONE].length = NUM_SAMPLES_PER_CHANNEL;

            /* Enable transfer */
            err = dtc_enable(&g_transfer_adc0_group_a_ctrl);
            handle_error(err, "\r\n** dtc_enable for unit 0 group A failed **\r\n", ALL);

            /* Reset the variable */
            g_adc0_group_a_flag = false;
        }
        /* Check if ADC 0 scan complete event for group B is received */
        else if (true == g_adc0_group_b_flag)
        {
            /* Buffer select for ping-pong buffer */
            static uint8_t buffer_select = ZERO;
            buffer_select = (buffer_select == ZERO) ? ONE : ZERO;

            /* Update destination address and length for transfer */
            g_transfer_adc_group_b[ZERO].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_0][ADC_GROUP_SCAN_B][ZERO][buffer_select][ZERO];
            g_transfer_adc_group_b[ONE].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_0][ADC_GROUP_SCAN_B][ONE][buffer_select][ZERO];
            g_transfer_adc_group_b[ZERO].length = NUM_SAMPLES_PER_CHANNEL;
            g_transfer_adc_group_b[ONE].length = NUM_SAMPLES_PER_CHANNEL;

            /* Enable transfer */
            err = dtc_enable(&g_transfer_adc0_group_b_ctrl);
            handle_error(err, "\r\n** dtc_enable for unit 0 group B failed **\r\n", ALL);

            /* Reset the variable */
            g_adc0_group_b_flag = false;
        }
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
        /* Check if ADC 1 scans complete event for group A is received */
        else if (true == g_adc1_group_a_flag)
        {
            /* Buffer select for ping-pong buffer */
            static uint8_t buffer_select = ZERO;
            buffer_select = (buffer_select == ZERO) ? ONE : ZERO;

            /* Update destination address and length for transfer */
            g_transfer_adc_group_a[TWO].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_1][ADC_GROUP_SCAN_A][ZERO][buffer_select][ZERO];
            g_transfer_adc_group_a[THREE].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_1][ADC_GROUP_SCAN_A][ONE][buffer_select][ZERO];
            g_transfer_adc_group_a[TWO].length   = NUM_SAMPLES_PER_CHANNEL;
            g_transfer_adc_group_a[THREE].length = NUM_SAMPLES_PER_CHANNEL;

            /* Enable transfer */
            err = dtc_enable(&g_transfer_adc1_group_a_ctrl);
            handle_error(err, "\r\n** dtc_enable for unit 1 group A failed **\r\n", ALL);

            /* Reset the variable */
            g_adc1_group_a_flag = false;
        }
        /* Check if ADC 1 scan complete event for group B is received */
        else if (true == g_adc1_group_b_flag)
        {
            /* Buffer select for ping-pong buffer */
            static uint8_t buffer_select = ZERO;
            buffer_select = (buffer_select == ZERO) ? ONE : ZERO;

            /* Update destination address and length for transfer */
            g_transfer_adc_group_b[TWO].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_1][ADC_GROUP_SCAN_B][ZERO][buffer_select][ZERO];
            g_transfer_adc_group_b[THREE].p_dest =
            (void*) &g_buffer_adc[ADC_UNIT_1][ADC_GROUP_SCAN_B][ONE][buffer_select][ZERO];
            g_transfer_adc_group_b[TWO].length = NUM_SAMPLES_PER_CHANNEL;
            g_transfer_adc_group_b[THREE].length = NUM_SAMPLES_PER_CHANNEL;

            /* Enable transfer */
            err = dtc_enable(&g_transfer_adc1_group_b_ctrl);
            handle_error(err, "\r\n** dtc_enable for unit 1 group B failed **\r\n", ALL);

            /* Reset the flag */
            g_adc1_group_b_flag = false;
        }
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */
        /* Check if ADC 1 or 0 scan complete event is not received */
#if (BSP_PERIPHERAL_ADC_B_PRESENT)
        else if (true == g_err_flag_adc_b)
        {
             handle_error(FSP_ERR_ABORTED,
                          "\r\n** ADC scan complete event for groups on unit 1 or 0 is not received **\r\n", ALL);
        }
#elif (BSP_PERIPHERAL_ADC_PRESENT)
#if (BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK)
        else if ((true == g_err_flag_adc0) || (true == g_err_flag_adc1))
        {
            handle_error(FSP_ERR_ABORTED,
                         "\r\n** ADC scan complete event for group A or B on unit 1 or 0 is not received **\r\n", ALL);
        }
#else
        else if (true == g_err_flag_adc0)
        {
            handle_error(FSP_ERR_ABORTED,
                         "\r\n** ADC scan complete event for group A or B on unit 0 is not received **\r\n", ALL);
        }
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */
#endif /* BSP_PERIPHERAL_ADC_B_PRESENT */
        else
        {
            /* Do nothing */
        }
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * @brief       Initialize and enable the ADC, GPT, DTC, and ELC modules for use as the signal acquisition module.
 * @param[in]   None.
 * @retval      None. All initialization steps are checked internally, and the system enters an error trap if any
 *              module fails to initialize.
 **********************************************************************************************************************/
static void general_signal_acquisition_init(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* Initialize all Event Link Controller (ELC) connections */
    err = init_hal_elc(&g_elc_ctrl, &g_elc_cfg);
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("\r\n** init_hal_elc failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Initialize DTC instance for ADC unit 0, group A, then reconfigure in chain mode */
    err = init_hal_dtc(&g_transfer_adc0_group_a_ctrl, &g_transfer_adc0_group_a_cfg);
    handle_error(err, "\r\n** init_hal_dtc for unit 0, group A failed **\r\n", ELC_MODULE);

    err = dtc_hal_reconfigure(&g_transfer_adc0_group_a_ctrl, &g_transfer_adc_group_a[ZERO]);
    handle_error(err, "\r\n** dtc_hal_reconfigure for unit 0, group A failed **\r\n", ELC_DTC1);

    /* Initialize DTC instance for ADC unit 0, group B, then reconfigure in chain mode */
    err = init_hal_dtc(&g_transfer_adc0_group_b_ctrl, &g_transfer_adc0_group_b_cfg);
    handle_error(err, "\r\n** init_hal_dtc for unit 0, group B failed **\r\n", ELC_DTC1);

    err = dtc_hal_reconfigure(&g_transfer_adc0_group_b_ctrl, &g_transfer_adc_group_b[ZERO]);
    handle_error(err, "\r\n** dtc_hal_reconfigure for unit 0, group B failed **\r\n", ELC_DTC12);

#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
    /* Initialize DTC instance for ADC unit 1, group A, then reconfigure in chain mode */
    err = init_hal_dtc(&g_transfer_adc1_group_a_ctrl, &g_transfer_adc1_group_a_cfg);
    handle_error(err, "\r\n** init_hal_dtc for unit 1, group A failed **\r\n", ELC_DTC12);

    err = dtc_hal_reconfigure(&g_transfer_adc1_group_a_ctrl, &g_transfer_adc_group_a[TWO]);
    handle_error(err, "\r\n** dtc_hal_reconfigure for unit 1, group A failed **\r\n", ELC_DTC_123);

    /* Initialize DTC instance for ADC unit 1, group B, then reconfigure in chain mode */
    err = init_hal_dtc(&g_transfer_adc1_group_b_ctrl, &g_transfer_adc1_group_b_cfg);
    handle_error(err, "\r\n** init_hal_dtc for unit 1, group B failed **\r\n", ELC_DTC_123);

    err = dtc_hal_reconfigure(&g_transfer_adc1_group_b_ctrl, &g_transfer_adc_group_b[TWO]);
    handle_error(err, "\r\n** dtc_hal_reconfigure for unit 1, group B failed **\r\n", ELC_DTC_MODULE_ALL);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */
    /* Initialize ADC unit 0 and configure its scan channels */
    err = init_hal_adc(&g_adc0_ctrl, &g_adc0_cfg);
    handle_error(err, "\r\n** init_hal_adc for unit 0 failed **\r\n", ELC_DTC_MODULE_ALL);

#ifdef BSP_PERIPHERAL_ADC_B_PRESENT
    err = adc_channel_config(&g_adc0_ctrl, &g_adc0_scan_cfg);
#else
    err = adc_channel_config(&g_adc0_ctrl, &g_adc0_channel_cfg);
#endif /* BSP_PERIPHERAL_ADC_B_PRESENT */
    handle_error(err, "\r\n** adc_channel_config for unit 0 failed **\r\n", ELC_DTC_ADC0_MODULE);

#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK
    err = init_hal_adc(&g_adc1_ctrl, &g_adc1_cfg);
    handle_error(err, "\r\n** init_hal_adc for unit 1 failed **\r\n", ELC_DTC_ADC0_MODULE);

    err = adc_channel_config(&g_adc1_ctrl, &g_adc1_channel_cfg);
    handle_error(err, "\r\n** adc_channel_config for unit 1 failed **\r\n", ELC_DTC_ADC_MODULE_ALL);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */
    /* Initialize GPT timer 0 */
    err = init_hal_gpt(&g_timer0_ctrl, &g_timer0_cfg);
    handle_error(err, "\r\n** init_hal_gpt for timer 0 failed **\r\n", ELC_DTC_ADC_MODULE_ALL);

    /* Enable Event Link Controller operation */
    err = elc_enable(&g_elc_ctrl);
    handle_error(err, "\r\n** elc_enable failed **\r\n", ALL);

    /* Enable DTC transfers for ADC unit 0 groups */
    err = dtc_enable(&g_transfer_adc0_group_a_ctrl);
    handle_error(err, "\r\n** dtc_enable for ADC unit 0 group A failed **\r\n", ALL);

    err = dtc_enable(&g_transfer_adc0_group_b_ctrl);
    handle_error(err, "\r\n** dtc_enable for ADC unit 0 group B failed **\r\n", ALL);

#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
    /* Enable DTC transfers for ADC unit 1 groups */
    err = dtc_enable(&g_transfer_adc1_group_a_ctrl);
    handle_error(err, "\r\n** dtc_enable for ADC unit 1 group A failed **\r\n", ALL);

    err = dtc_enable(&g_transfer_adc1_group_b_ctrl);
    handle_error(err, "\r\n** dtc_enable for ADC unit 1 group B failed **\r\n", ALL);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */
}

/*******************************************************************************************************************//**
 * @brief       Handle an error by printing a message, closing related modules, and entering an error trap.
 * @param[in]   err       Error status returned from an FSP API.
 * @param[in]   err_str   Error message to print before trapping.
 * @param[in]   module    Indicates which modules must be closed before trapping.
 * @retval      None.
 **********************************************************************************************************************/
static void handle_error(fsp_err_t err, char *err_str, module_name_t module)
{
    if (FSP_SUCCESS != err)
    {
        switch (module)
        {
            case ELC_MODULE:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);
                break;
            }

            case ELC_DTC1:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close DTC instance for ADC unit 0, group A */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                break;
            }

            case ELC_DTC12:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close DTC instances for ADC unit 0, groups A and B */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
                break;
            }

#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
            case ELC_DTC_123:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close DTC instances for ADC unit 0 (A, B) and unit 1 (A) */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_a_ctrl);
                break;
            }

            case ELC_DTC_MODULE_ALL:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close all DTC instances */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_b_ctrl);
                break;
            }

#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */
            case ELC_DTC_ADC0_MODULE:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close all DTC instances */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
                deinit_hal_dtc(&g_transfer_adc1_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_b_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */

                /* Close ADC instance */
                deinit_hal_adc(&g_adc0_ctrl);
                break;
            }

            case ELC_DTC_ADC_MODULE_ALL:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close all DTC instances */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
                deinit_hal_dtc(&g_transfer_adc1_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_b_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */

                /* Close ADC instances */
                deinit_hal_adc(&g_adc0_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK
                deinit_hal_adc(&g_adc1_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */
                break;
            }

            case ELC_DTC_ADC_GPT0_MODULE:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close DTC instances */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
                deinit_hal_dtc(&g_transfer_adc1_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_b_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */

                /* Close ADC instances */
                deinit_hal_adc(&g_adc0_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK
                deinit_hal_adc(&g_adc1_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */

                /* Close GPT timer 0 instance */
                deinit_hal_gpt(&g_timer0_ctrl);
                break;
            }

            case ALL:
            {
                /* Close ELC instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* Close ADC instances */
                deinit_hal_adc(&g_adc0_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK
                deinit_hal_adc(&g_adc1_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK */

                /* Close GPT instance */
                deinit_hal_gpt(&g_timer0_ctrl);

                /* Close all DTC instances */
                deinit_hal_dtc(&g_transfer_adc0_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc0_group_b_ctrl);
#if BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK
                deinit_hal_dtc(&g_transfer_adc1_group_a_ctrl);
                deinit_hal_dtc(&g_transfer_adc1_group_b_ctrl);
#endif /* BSP_FEATURE_ADC_UNIT_1_CHANNELS_MASK || BSP_FEATURE_ADC_B_UNIT_1_CHANNELS_MASK */
                break;
            }

            default:
            {
                /* Do nothing */
                break;
            }
        }
        APP_PRINT(err_str);
        APP_ERR_TRAP(err);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup adc_gpt_periodic_sampling_ep)
 **********************************************************************************************************************/
