/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2023 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "ceu.h"
#include "ov3640.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* External variables */
extern uint32_t g_image_width;
extern uint32_t g_image_height;
extern uint8_t * gp_image_buffer;
extern sensor_reg_t const * gp_ov3640_resolution;
extern capture_instance_t const * gp_ceu_instance;


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t  version = {RESET_VALUE};
    fsp_err_t           err     = FSP_SUCCESS;

    /* Version get API for FSP pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the RTT */
    APP_PRINT (BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT_WAIT;
    APP_PRINT (EP_INFO);
    APP_PRINT_WAIT;

#if !defined (BOARD_RA8E1_FPB)
    /* Initialize SDRAM */
    R_BSP_SdramInit(true);
#endif
    /* Initialize GPT module */
    err = R_GPT_Open(&g_timer_periodic_ctrl, &g_timer_periodic_cfg);
    handle_error(err, " ** R_GPT_Open API FAILED ** \r\n");

    /* Start GPT module to provide the 24MHz clock frequency output for the camera clock source */
    err = R_GPT_Start(&g_timer_periodic_ctrl);
    handle_error(err, " ** R_GPT_Start API FAILED ** \r\n");

    /* Initialize IIC module */
    err = R_IIC_MASTER_Open(&g_i2c_master_for_ov3640_ctrl, &g_i2c_master_for_ov3640_cfg);
    handle_error(err, " ** R_IIC_MASTER_Open API FAILED ** \r\n");

    /* Initialize OV3640 sensor with output format as YUV422 */
    err = ov3640_open();
    handle_error(err, " ** ov3640_open FAILED ** \r\n");

    /* Main loop */
    while(true)
    {
        /* User selects type of memory to store image and resolution of image */
        selection_menu();

        /* Set camera resolution specified by ov3640 array pointer */
        err = ov3640_set_resolution(gp_ov3640_resolution);
        handle_error(err, " ** ov3640_set_resolution FAILED ** \r\n");

        /* Perform CEU operation specified by ceu instance pointer and store image in buffer specified by image buffer pointer */
        err = ceu_operation(gp_ceu_instance, gp_image_buffer, g_image_width, g_image_height);
        handle_error(err, " ** ceu_operation FAILED ** \r\n");
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}


/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
