/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and initialize application data in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2019 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "Application.h"
#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

static day_info_t forecast[7] =
{
    { "SUN", "Sunny",         "72", "81", "84/73"},
    { "MON", "Partly Cloudy", "50", "74","77/67"},
    { "TUE", "Partly Cloudy", "52", "71","74/65"},
    { "WED", "Rain",          "99", "65", "68/60"},
    { "THU", "Showers",       "85", "73", "76/70"},
    { "FRI", "Partly Cloudy", "50", "80", "83/72"},
    { "SAT", "Sunny",         "45", "89", "92/77"}
};

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
		/* Initialize application data, once after RESET */
        gDataApp.bgrd_darmode           = 0;
        gDataApp.pwm_duty_cycle         = 50;
        gDataApp.text_color             = 0;
        gDataApp.forecast_info          = &forecast[0];
        gDataApp.thermo_target_temp     = 70;
        gDataApp.current_forecast       = WEEK_DAY_SUN;
        gDataApp.sys_weather_type       = SYS_WEATHER_SUNNY;
        gDataApp.total_forecast         = 7;
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
