/**********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
 * THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2021,2022 Renesas Electronics Corporation. All rights reserved.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * File Name    : new_aes_key.c
 * Version      : 1.00
 * Device(s)    : RA,RE,RX,RZ,Synergy Family
 * Description  : Key data generated by the Security Key Management Tool v1.02
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * History : DD.MM.YYYY Version  Description
 *         : 31.12.2021 1.00     First Release
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include "new_aes_key.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Local Typedef definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Exported global variables
 *********************************************************************************************************************/
const NEW_AES256_t g_NEW_AES256 =
{
    /* uint32_t keytype; */
    0x00000007,
    /* uint32_t shared_key_number; */
    0x00000000,
    /* uint8_t initial_vector[16]; */
    {
        0x7F, 0x27, 0xA6, 0x10, 0x92, 0x55, 0x02, 0xA8, 0x09, 0xBF, 0x06, 0x6A, 0x8F, 0x76, 0xF9, 0x50
    },
    /* uint8_t encrypted_user_key[NEW_AES256_BYTE_SIZE]; */
    {
        0x76, 0x68, 0x69, 0x7C, 0x91, 0xD0, 0x14, 0x99, 0x2E, 0x33, 0x4D, 0x22, 0x1E, 0x3B, 0xBA, 0x14,
        0x1D, 0x96, 0x14, 0xA4, 0x83, 0xBB, 0x34, 0x66, 0x24, 0x6C, 0xDD, 0xB5, 0x73, 0xCF, 0xEA, 0x90,
        0xE8, 0xB8, 0x7D, 0xA4, 0xBA, 0xC1, 0x5F, 0x89, 0x3E, 0x7C, 0x3D, 0x4F, 0xA2, 0x5D, 0x4D, 0x9D
    },
    /* uint8_t crc[4]; */
    {
        0xC2, 0xB7, 0x9C, 0x10
    },
};

/**********************************************************************************************************************
 Private (static) variables and functions
 *********************************************************************************************************************/

