/***********************************************************************************************************************
 * File Name    : system_thread_entry.c
 * Description  : Contains entry function of system control.
 ***********************************************************************************************************************/
/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#include <guix_gen/thermostat_resources.h>
#include <guix_gen/thermostat_specifications.h>
#include "ospi_b_commands.h"

#define APP_ERR_TRAP(err)           if(err) { __asm("BKPT #0\n");} /* trap upon the error  */ // @suppress("3.9b, 3.9f, 8.4b Macro expansion")
#define GUI_MEM_SDRAM_POOL (783360U)

TX_BYTE_POOL g_guix_pool_sdram;
UCHAR g_mem_guix_pool_sdram[GUI_MEM_SDRAM_POOL] BSP_ALIGN_VARIABLE(8) BSP_PLACE_IN_SECTION(".sdram");


/* Root Window and screen pointers */
GX_WINDOW*      p_splash_screen;
GX_WINDOW*      p_mainpage_screen;
GX_WINDOW_ROOT* p_root;

#if 0
/* Mesage Queue*/
TX_QUEUE systen_msg_queue;
TX_BYTE_POOL   byte_pool;
static uint8_t byte_memory[BYTE_POOL_SIZE] = {'\0'};
static uint8_t queue_memory_system_obj[20] = {'\0'};
static CHAR *byte_pool_name = "system_processing_block";
#endif
/***********************************************************************************************************************
 Private functions
 ***********************************************************************************************************************/


/** Stored GUI state. */


/* System Thread entry function */
void system_thread_entry(void)
{
    UINT          gx_err         = GX_SUCCESS;

    /* Initializes GUIX. */
    gx_err = gx_system_initialize();
    if(TX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Configure main display */
    gx_err = gx_studio_display_configure(DISPLAY,
                                rm_guix_port_hw_initialize,
                                LANGUAGE_ENGLISH,
                                DISPLAY_THEME_1,
                                &p_root);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Set pointer to the first buffer generated by the configuration (rm_guix_port_canvas) */
    gx_err = gx_canvas_memory_define(p_root->gx_window_root_canvas,
                            rm_guix_port_canvas,
                            p_root->gx_window_root_canvas->gx_canvas_memory_size);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Create the widget and attached to root window.*/
    gx_err = gx_studio_named_widget_create("Splash", (GX_WIDGET *) p_root, (GX_WIDGET **) &p_splash_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    gx_err = gx_studio_named_widget_create ("MainPage", GX_NULL, (GX_WIDGET **) &p_mainpage_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Shows the root window. */
    gx_err = gx_widget_show(p_root);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Start GUIX */
    gx_err = gx_system_start();
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    while (1)
    {
        tx_thread_sleep (1);
    }
}
