/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/**********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*********************************************************************************************************************/

#include "hal_data.h"
#include "arm_dsp_example.h"
#include "arm_dsp_example_config.h"
#include "led.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
#if ARM_FIR_EXAMPLE
    main_arm_fir_example_f32();
#endif
#if ARM_FFT_BIN_EXAMPLE
    main_arm_fft_bin_example_f32();
#endif
#if ARM_SIN_COS_EXAMPLE
    main_arm_sin_cos_example_f32();
#endif
#if ARM_SIGNAL_CONVERGE_EXAMPLE
    main_arm_signal_converge_example_f32();
#endif
#if ARM_DOTPRODUCT_EXAMPLE
    main_arm_dotproduct_example_f32();
#endif
#if ARM_LINEAR_INTERP_EXAMPLE
    main_arm_linear_interp_example_f32();
#endif
#if ARM_GRAPHIC_EQUALIZER_EXAMPLE
    main_arm_graphic_equalizer_example_q31();
#endif
#if ARM_VARIANCE_EXAMPLE
    main_arm_variance_example_f32();
#endif
#if ARM_CONVOLUTION_EXAMPLE
    main_arm_convolution_example_f32();
#endif
#if ARM_CLASS_MARKS_EXAMPLE
    main_arm_class_marks_example_f32();
#endif
#if ARM_MATRIX_EXAMPLE
    main_arm_matrix_example_f32();
#endif
#if ARM_SVM_EXAMPLE
    main_arm_svm_example_f32();
#endif
#if ARM_BAYES_EXAMPLE
    main_arm_bayes_example_f32();
#endif

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
