/**********************************************************************************************************************
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*********************************************************************************************************************/

#include "hal_data.h"
#include "arm_dsp_example.h"
#include "arm_dsp_example_config.h"
#include "led.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{

#if ARM_FIR_EXAMPLE
    main_arm_fir_example_f32();
#endif
#if ARM_FFT_BIN_EXAMPLE
    main_arm_fft_bin_example_f32();
#endif
#if ARM_SIN_COS_EXAMPLE
    main_arm_sin_cos_example_f32();
#endif
#if ARM_SIGNAL_CONVERGE_EXAMPLE
    main_arm_signal_converge_example_f32();
#endif
#if ARM_DOTPRODUCT_EXAMPLE
    main_arm_dotproduct_example_f32();
#endif
#if ARM_LINEAR_INTERP_EXAMPLE
    main_arm_linear_interp_example_f32();
#endif
#if ARM_GRAPHIC_EQUALIZER_EXAMPLE
    main_arm_graphic_equalizer_example_q31();
#endif
#if ARM_VARIANCE_EXAMPLE
    main_arm_variance_example_f32();
#endif
#if ARM_CONVOLUTION_EXAMPLE
    main_arm_convolution_example_f32();
#endif
#if ARM_CLASS_MARKS_EXAMPLE
    main_arm_class_marks_example_f32();
#endif
#if ARM_MATRIX_EXAMPLE
    main_arm_matrix_example_f32();
#endif
#if ARM_SVM_EXAMPLE
    main_arm_svm_example_f32();
#endif
#if ARM_BAYES_EXAMPLE
    main_arm_bayes_example_f32();
#endif
#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
