/***********************************************************************************************************************
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/
#include "common_utils.h"
#include "ospi_commands.h"
#include "ospi_ep.h"


FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Private Function Declaration */
void reset_device(void);

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {

    fsp_pack_version_t version            = {RESET_VALUE};
    fsp_err_t          err                =  FSP_SUCCESS;
    uint8_t            read_data          = RESET_VALUE;
    uint32_t           dev_id             = RESET_VALUE;
    bsp_octaclk_settings_t octaclk        = {RESET_VALUE};

    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Reset device */
    reset_device();

    /* Upon power-on or reset, the device defaults to SPI mode.
     * To ensure proper operation, the OCTACLK clock should be configured to 100 MHz in SPI mode.
     * Because OM_SCLK (OM_SCLK = OCTACLK/2) only support 50MHz as max.
     */
    octaclk.source_clock = BSP_CFG_OCTA_SOURCE;  /* 200MHz */
    octaclk.divider      = BSP_CLOCKS_OCTA_CLOCK_DIV_2;
    R_BSP_OctaclkUpdate(&octaclk);

    /* Initialize the OSPI driver module.*/
    err = ospi_init();
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT ("\r\n** OSPI INIT FAILED **\r\n");
        APP_ERR_TRAP(err);
    }

    /*Enable Write */
    err = ospi_write_enable_and_verify(&g_ospi_ctrl, SPI_FLASH_PROTOCOL_EXTENDED_SPI);
    if (FSP_SUCCESS != err)
    {
        /*handle error*/
        handle_error(err, "\r\n** OSPI Write Enable and Verify failed **\r\n");
    }

    /* configure ospi in extended spi mode */
    err = reconfigure_device();
    if(FSP_SUCCESS != err)
    {
        /*handle error*/
        handle_error(err, "\r\n** Reconfiguring OSPI device failed  **\r\n");
    }

    /*Read the device id*/
    err = read_device_id(&dev_id);
    if(FSP_SUCCESS != err)
    {
        /*handle error*/
        handle_error(err, "\r\n** Device_ID read operation failed **\r\n");
    }

    /* Reset the OCTACLK clock to 200 MHz, as specified by the default configuration.*/
    octaclk.source_clock = BSP_CFG_OCTA_SOURCE;  /* 200MHz */
    octaclk.divider      = BSP_CFG_OCTA_DIV;
    R_BSP_OctaclkUpdate(&octaclk);

    /*Print device id and main menu*/
    APP_PRINT("\nDevice ID read successfully and Device id : 0x%X\r\n",dev_id);
    APP_PRINT(OSPI_MENU);

    while(true)
    {
        /* read user input */
        read_data = process_input_data();
        switch (read_data)
        {
            /*Perform Extended SPI Operation*/
            case SPI_MODE:
            {
                err = spi_operation();
                /*handle error*/
                handle_error(err, "\r\n** SPI Operation failed **\r\n");
                break;
            }

            /*Perform SOPI operation*/
            case SOPI_MODE:
            {
                err = opi_operation(SOPI_OPERATION_MODE);
                /*handle error*/
                handle_error(err, "\r\n** SOPI Operation failed **\r\n");
                break;
            }

            /*Perform DOPI operation*/
            case DOPI_MODE:
            {
                err = opi_operation(DOPI_OPERATION_MODE);
                /*handle error*/
                handle_error(err, "\r\n** DOPI Operation failed **\r\n");
                break;
            }

            default:
            {
                APP_PRINT ("\r\n Invalid input. Provide a valid input\r\n");
                break;
            }

        }
        /*reset data */
        read_data = RESET_VALUE;
        /* Print Main Menu option of OSPI operation.*/
        APP_PRINT(OSPI_MENU);
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event) {
    if (BSP_WARM_START_RESET == event) {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event) {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif

/*****************************************************************************************************************
 *  @brief      Resets the flash device
 *  @param[in]  None
 *  @retval     None
 ****************************************************************************************************************/
void reset_device()
{
    /* OSPI Memory reset Pin */
    R_IOPORT_PinWrite(&g_ioport_ctrl, RESET_PIN, BSP_IO_LEVEL_LOW);
    R_BSP_SoftwareDelay(DELAY_TIME, BSP_DELAY_UNITS_MICROSECONDS);
    R_IOPORT_PinWrite(&g_ioport_ctrl, RESET_PIN, BSP_IO_LEVEL_HIGH);
    R_BSP_SoftwareDelay(DELAY_TIME, BSP_DELAY_UNITS_MICROSECONDS);
}
