#######################################################################################################################
# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
# other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
# THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
# EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
# SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
# THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
# this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
#######################################################################################################################
# LLVM Error workaround: Import torch first before importing tvm.
# https://discuss.tvm.apache.org/t/llvm-error-when-tracing-maskrcnn-model-in-pytorch-object-detection-tutorial/10066
import torch
import onnx

from tvm import relay

from renesas_aicompiler_caller.utils import LogFactory
from renesas_aicompiler_caller.commands.tvm.utils import get_onnx_shape_dict, \
                                                  convert_shape_dict2list_of_tuple, \
                                                  _validate_shape_dict_w_model_shape_dict

__all__ = ['run_frontend_compiler']

logger = LogFactory().add_console_handler() \
                     .build(__name__)


################################################################################
# Frontend utility functions
################################################################################
def run_frontend_compiler(framework,
                          input_model,
                          shape_dict=None):
    """Run frontend compiler

    Args:
        framework: Framework of input model file. This option can be set onnx, pytorch or tflite.
        input_model: Path to input model file.
        shape_dict: The input shape to the graph.

    Returns:
        mod: IR format AI model generated by TVM frontend.
        params: Parameter date generated by TVM frontend.
        shape_dict: The input shape to the graph.
    """

    if "onnx" == framework:
        mod, params, shape_dict = run_onnx_frontend_compiler(input_model,
                                                             shape_dict)
        return mod, params, shape_dict

    elif "pytorch" == framework:
        mod, params, shape_dict = run_pytorch_frontend_compiler(input_model,
                                                                shape_dict)
        return mod, params, shape_dict

    elif "tflite" == framework:
        mod, params, shape_dict = run_tflite_frontend_compiler(input_model,
                                                               shape_dict)
        return mod, params, shape_dict

    else:
        raise NotImplementedError("Unsupported framework. `framework` can be set to onnx, pytorch or tflite.")


def run_onnx_frontend_compiler(input_model,
                               shape_dict=None):
    """Run onnx frontend compiler
    Args:
        input_model: Path to onnx model file.
        shape_dict: The input shape to the graph

    Returns:
        mod: IR format AI model generated by TVM frontend.
        params: Parameter date generated by TVM frontend.
        shape_dict: The input shape to the graph.
    """
    logger.info("Run onnx frontend compiler.")

    # 2. Load onnx model and set input shape.
    # 2.1 Load onnx model
    onnx_model = onnx.load_model(input_model)

    # 2.2 Set input data information
    onnx_shape_dict = get_onnx_shape_dict(onnx_model)
    logger.info(f"onnx_shape_dict: {onnx_shape_dict}")
    if shape_dict is None:
        shape_dict = onnx_shape_dict
    else:
        _validate_shape_dict_w_model_shape_dict(shape_dict, onnx_shape_dict)

    # 3.1 Run TVM Frontend
    mod, params = relay.frontend.from_onnx(onnx_model, shape_dict)
    return mod, params, shape_dict


def run_pytorch_frontend_compiler(input_model,
                                  shape_dict):
    """Run pytorch frontend compiler

    Args:
        input_model: Path to pytorch (torchscripted) model file.
        shape_dict: The input shape to the graph

    Returns:
        mod: IR format AI model generated by TVM frontend.
        params: Parameter date generated by TVM frontend.
        shape_dict: The input shape to the graph.
    """
    logger.info("Run pytorch frontend compiler.")

    # Load pytorch model
    torch_model = torch.jit.load(input_model)
    torch_model.eval()

    # Set input data information
    logger.info(f"shape_dict: {shape_dict}")
    shape_list = convert_shape_dict2list_of_tuple(shape_dict)
    logger.info(f'shape_list: {shape_list}')

    # 3.1 Run TVM Frontend
    mod, params = relay.frontend.from_pytorch(torch_model, shape_list)

    return mod, params, shape_dict


def run_tflite_frontend_compiler(input_model,
                                 shape_dict=None):
    """Run tflite frontend compiler

    Args:
        input_model: Path to tflite model file.
        shape_dict: The input shape to the graph

    Returns:
        mod: IR format AI model generated by TVM frontend.
        params: Parameter date generated by TVM frontend.
        shape_dict: The input shape to the graph.
    """
    import tflite
    logger.info("Run tflite frontend compiler.")

    # 2. Load tflite model
    tflite_model_buf = open(input_model, "rb").read()
    tflite_model = tflite.Model.GetRootAsModel(tflite_model_buf, 0)

    # 2.2 Set input data information
    tflite_shape_dict, _ = relay.frontend.tflite._input_type(tflite_model)
    if shape_dict is None:
        shape_dict = tflite_shape_dict
    else:
        _validate_shape_dict_w_model_shape_dict(shape_dict, tflite_shape_dict)

    # 3.1 Run TVM Frontend
    mod, params = relay.frontend.from_tflite(tflite_model,
                                             shape_dict=shape_dict)

    return mod, params, shape_dict
