#######################################################################################################################
# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
# other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
# THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
# EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
# SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
# THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
# this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
#######################################################################################################################
from tvm.relay.mera import drp

from renesas_aicompiler_caller.utils import LogFactory
from renesas_aicompiler_caller.commands.tvm.utils import BaseModelConverter, \
                                                  run_frontend_compiler, \
                                                  register_model_converter

logger = LogFactory().add_console_handler() \
                     .build(__name__)


@register_model_converter
class V111RzV2lModelConverter(BaseModelConverter):

    def __init__(self):
        super().__init__()

    def execute_frontend(self,
                         framework,
                         input_model,
                         shape_dict,
                         **kwargs):
        """Run frontend compiler

        Args:
            framework: Framework of input model file. This option can be set onnx, pytorch or tflite.
            input_model: Path to input model file.
            shape_dict: The input shape to the graph.

        Returns:
            mod: IR format AI model generated by TVM frontend.
            params: Parameter date generated by TVM frontend.
            shape_dict: The input shape to the graph.
        """
        logger.info("Run TVM frontend compiler with DRP-AI Translator.")
        mod, params, shape_dict = run_frontend_compiler(framework=framework,
                                                        input_model=input_model,
                                                        shape_dict=shape_dict)
        return mod, params, shape_dict

    def execute_backend(self,
                        mod,
                        params,
                        output_dir,
                        target_architecture="arm",
                        disable_concat=False,
                        interpreter=None,
                        addr_map_start=0x838E0000,
                        toolchain_dir="/opt/drp-ai_translator_release",
                        sdk_root="/opt/poky/3.1.17",
                        **kwargs
                        ):
        """Run DRP-AI backend compiler

        Args:
            mod: IR format AI model generated by TVM frontend.
            params: Parameter date generated by TVM frontend.
            output_dir: Output directory to save compile results.
            target_architecture: Target architecture. Supported "arm" only.
            disable_concat: Disable concat optimization.

            interpreter: [Deprecated] Although it was deprecated in DRP-AI TVM v2.1.0, \
                the argument is kept for backward compatibility.
            addr_map_start: The memory address that DRP-AI TVM Model Object is deployed.
            toolchain_dir: Path to root directory of DRP-AI Translator
            sdk_root: SDK(Cross compiler) installed directory.

        Returns:
            None
        """
        logger.info("Run TVM backend compiler with DRP-AI Translator.")

        # 3.2.1 Set config for DRP-AI runtime
        drp_config_runtime = {
            "interpreter": interpreter,
            "addr_map_start": addr_map_start,
            "toolchain_dir": toolchain_dir,
            "sdk_root": sdk_root
        }

        # 3.2.2 Run backend compiler
        drp.build(mod,
                  params,
                  target_architecture,
                  drp_config_runtime,
                  output_dir=output_dir,
                  disable_concat=disable_concat)
