#######################################################################################################################
# DISCLAIMER
# This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
# other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
# applicable laws, including copyright laws.
# THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
# THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
# EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
# SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
# THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
# this software. By using this software, you agree to the additional terms and conditions found by accessing the
# following link:
# http://www.renesas.com/disclaimer
#
# Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
#######################################################################################################################
import os
import json
from typing import List
from tvm.relay.mera import drp

import pathlib
import numpy as np
import re
from PIL import Image

from drpai_quantizer import CalibrationDataReader

from renesas_aicompiler_caller.utils import LogFactory
from renesas_aicompiler_caller.commands.tvm.utils import BaseModelConverter, \
                                                  run_frontend_compiler, \
                                                  register_model_converter, \
                                                  _validate_datareader_inputs, \
                                                  _validate_channel_num

logger = LogFactory().add_console_handler() \
                     .build(__name__)

IMAGE_DIM_LENGTH = 4


@register_model_converter
class V221RzV2hModelConverter(BaseModelConverter):

    def __init__(self):
        super().__init__()

    def execute_frontend(self,
                         framework,
                         input_model,
                         shape_dict,
                         **kwargs):
        """Run frontend compiler

        Args:
            framework: Framework of input model file. This option can be set onnx, pytorch or tflite.
            input_model: Path to input model file.
            shape_dict: The input shape to the graph.

        Returns:
            mod: IR format AI model generated by TVM frontend.
            params: Parameter date generated by TVM frontend.
            shape_dict: The input shape to the graph.
        """
        logger.info("Run TVM frontend compiler with DRP-AI Translator.")
        mod, params, shape_dict = run_frontend_compiler(framework=framework,
                                                        input_model=input_model,
                                                        shape_dict=shape_dict)
        return mod, params, shape_dict

    def execute_backend(self,
                        mod,
                        params,
                        output_dir,
                        target_architecture="arm",
                        disable_concat=False,
                        interpreter=None,
                        addr_map_start=0x838E0000,
                        toolchain_dir="/opt/drp-ai_translator_release",
                        sdk_root="/opt/poky/3.1.17",
                        **kwargs
                        ):
        """Run DRP-AI backend compiler for v2h

        Args:
            mod: IR format AI model generated by TVM frontend.
            params: Parameter date generated by TVM frontend.
            output_dir: Output directory to save compile results.
            target_architecture: Target architecture. Supported "arm" only.
            disable_concat: Disable concat optimization.

            interpreter: [Deprecated] Although it was deprecated in DRP-AI TVM v2.1.0, \
                the argument is kept for backward compatibility.
            addr_map_start: The memory address that DRP-AI TVM Model Object is deployed.
            toolchain_dir: Path to root directory of DRP-AI Translator
            sdk_root: SDK(Cross compiler) installed directory.

        Returns:
            None
        """
        logger.info("Run TVM backend compiler with DRP-AI Translator.")

        # Settings
        # Directory containing the data to calibrate the model.
        record_dir = os.path.join(output_dir, '.data')
        opts = {
            # DRP-AI Translator version (091 or 100)
            "drp_compiler_version": "100",
            # Specify cpu data type (float16 or float32)
            "cpu_data_type": "float16",
        }
        opts.update(kwargs)
        logger.info(f"Backend options: \n{opts}")

        # 3.2.2 Run the backend compiler for x86 and generate reference output.
        drp_config = {
            "target": "Fp32DataRecorder",
            "drp_compiler_version": opts["drp_compiler_version"],
            "record_dir": record_dir,
        }
        json, _params, lib_path = drp.build(mod,
                                            params,
                                            "x86",
                                            drp_config,
                                            output_dir=os.path.join(output_dir, "_fp32_x86_out"),
                                            disable_concat=disable_concat,
                                            cpu_data_type=opts["cpu_data_type"])
        rt_mod = get_rt_mod(json, _params, lib_path)

        # Generate reference output
        logger.info("Generate the fp32 reference output.")
        """The following processes have been added to the tutorial code to support the GUI.
        For example, GUI can be used several file format for calibration
        compared with tutorial code such as compile_onnx_model_quant.py.
        """
        calib_info = get_datareader_calibinfo(opts["shape_dict"], opts["nodes"])
        logger.info(f"Calibration information for datareader: {calib_info}")
        data_reader = BackendCalibrationDataReader(num_calibrate_samples=opts["num_calibrate_samples"],
                                                   calibration_info=calib_info,
                                                   trans_nhwc2nchw=opts["trans_nhwc2nchw"])
        """End
        """
        # Execute inference to create calibration data for quantization.
        exec_tvm_inference(data_reader, rt_mod)

        # Adjust the quantization options to configure for TVM API
        quant_options = get_quant_options(opts)
        logger.info(f"Quantization options: {quant_options}")

        # 3.3.1 Set config for with x86 runtime with int8.
        drp_config = {
            "target": "InterpreterQuant",
            "drp_compiler_version": opts["drp_compiler_version"],
            "quantization_tool": opts["quantization_tool_dir"],
            "quantization_option": quant_options,
            "calibration_data": record_dir
        }
        json, _params, lib_path = drp.build(mod,
                                            params,
                                            "x86",
                                            drp_config,
                                            output_dir=os.path.join(output_dir, "_int8_x86_out"),
                                            disable_concat=disable_concat,
                                            cpu_data_type=opts["cpu_data_type"])
        rt_mod = get_rt_mod(json, _params, lib_path)
        logger.info("Generate the int8 reference output.")
        """The following processes have been added to the tutorial code to support the GUI.
        """
        data_reader.reset()
        data_reader.save_calib_data_list(os.path.join(output_dir, "_reference"))
        """End
        """
        ref_output = None
        # Remove comment out if you want to get int8 reference output.
        # ref_output = os.path.join(output_dir, "_reference/x86_int8")
        # Execute inference to verify that the quantization results work properly
        exec_tvm_inference(data_reader,
                           rt_mod,
                           output_dir=ref_output)

        # DrpAi translates onnx quantizer
        # 3.4 Run TVM backend with DRP-AI translator
        # 3.4.1 Set config for DRP-AI runtime with quantized int8.
        drp_config_runtime = {
            "target": "DrpAiQuant",
            "addr_map_start": addr_map_start,
            "toolchain_dir": toolchain_dir,
            "sdk_root": sdk_root,
            "drp_compiler_version": opts["drp_compiler_version"],
            "quantization_tool": opts["quantization_tool_dir"],
            "quantization_option": quant_options,
            "calibration_data": record_dir
        }
        # 3.4.2 Run backend compiler with Quantizeer.
        drp.build(mod,
                  params,
                  target_architecture,
                  drp_config_runtime,
                  output_dir=output_dir,
                  disable_concat=disable_concat,
                  cpu_data_type=opts["cpu_data_type"])


class BackendCalibrationDataReader(CalibrationDataReader):
    """Calibration data reader to be used in backend compiler

    Args:
        num_calibrate_samples: Number of calibration samples. \
        If -1, this datareader uses all data where are stored in calibration data directory.
        calibration_info: Dictionary containing mean and standard deviation for each nodes. \
        For more details about this data, refer to the `get_datareader_calibinfo`.
        trans_nhwc2nchw: If True, transpose input data from NHWC to NCHW. \
            N: number of data (fixed 1) \
            C: number of channels \
            H: height \
            W: width
    """
    def __init__(self, num_calibrate_samples, calibration_info, trans_nhwc2nchw=True):

        # Generate the random images if calibrate_sample_dir is "".
        import tempfile
        MAX_NUM_RANDOM_IMAGES = 5
        np.random.seed(0)
        # This loop iterates the number of times equal to the number of input nodes.
        for input_name, values in calibration_info.items():
            if values["calibrate_sample_dir"] != "":
                continue

            # Create a directory to store the random image
            temp_dir = tempfile.mkdtemp()
            calibration_info[input_name]["calibrate_sample_dir"] = temp_dir

            logger.info(f"Generate sample images with npy extension to {temp_dir=}...")
            generated_sample_size = max(num_calibrate_samples, MAX_NUM_RANDOM_IMAGES)
            mean = calibration_info[input_name]["mean"]
            std = calibration_info[input_name]["std"]
            try:
                # Generates a specified number of random data
                generate_random_data_as_npy(values["shape"],
                                            mean,
                                            std,
                                            generated_sample_size,
                                            temp_dir,
                                            trans_nhwc2nchw)
            except Exception:
                raise RuntimeError("Failed to generate the random data. "
                                   "It may be due to division by zero. "
                                   "Check the standard deviation setting on the GUI. "
                                   "If the current setting is 0, adjust it to a non-zero value.")

        # Get file paths to be used in calibration
        glob_file_ext_pattern = r".*\.(jpg|jpeg|png|gif|bmp|tif|tiff|npy)$"
        new_sample_size = np.iinfo(np.int64).max
        for input_name, values in calibration_info.items():
            temp_path = pathlib.Path(values["calibrate_sample_dir"])
            file_list = [p for p in temp_path.glob("**/*")
                         if re.search(glob_file_ext_pattern, str(p), re.IGNORECASE)]
            calibration_info[input_name].update({"file_list": file_list})

            # Find minimal sample size
            new_sample_size = min(new_sample_size, len(file_list))

        # Update minimal samle size
        if num_calibrate_samples != -1:
            new_sample_size = min(new_sample_size, num_calibrate_samples)

        # Pick up calibration data to align the number of samples to minimal sample size
        np.random.seed(0)
        all_filepath_list = []
        all_input_name_list = []
        for input_name, values in calibration_info.items():
            new_file_list = np.random.choice(values["file_list"],
                                             size=new_sample_size,
                                             replace=False)
            calibration_info[input_name].update({"file_list": new_file_list})
            all_filepath_list.append(new_file_list)
            all_input_name_list.append(input_name)

        self._num_calibrate_samples = new_sample_size
        logger.info(f"Calibration data size: {self._num_calibrate_samples}")
        if self._num_calibrate_samples <= 0:
            raise RuntimeError("Failed to find files to be used in calibration. \n"
                               "Please check whether your calibration data directory contains data or "
                               "please edit the BackendCalibrationDataReader to match your data type. \n"
                               "This data reader supports the following extensions \n"
                               "- gif, jpeg, jpg, png, bmp, tif, tiff, npy")

        # Make filepath iterator to be used in get_next() function.
        all_filepath = []
        for filpaths in zip(*all_filepath_list):
            all_filepath.append(filpaths)
        self._all_file_path = all_filepath
        self._all_filepath_iter = iter(self._all_file_path)
        self._all_input_name = all_input_name_list
        self._calibration_info = calibration_info
        self._trans_nhwc2nchw = trans_nhwc2nchw

    def preprocess_func(self, filepath, width, height,
                        mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]):
        """Preprocess function to be applied at get_next() function.
            This function applies the following preprocessing.
            1. Load image
            2. Convert to RGB (Not applicable if the original image is grayscale)
            3. Resize
            4. Normalize

        Args:
            filepath: Path to load the image file
            width: width after applying resize preprocessing
            height: height after applying resize preprocessing
            mean: List containing mean value to be used in normalize preprocessing.
            std: List containing standard deviation value to be used in normalize preprocessing.

        Returns:
            input_data: numpy array.
        """
        pillow_img = Image.open(filepath).resize((width, height))

        if pillow_img.mode == "L":
            pillow_img = np.expand_dims(pillow_img, axis=-1)
        elif pillow_img.mode != "RGB":
            pillow_img = pillow_img.convert("RGB")

        input_data = np.float32(pillow_img)
        input_data = input_data - mean
        input_data = input_data / std
        input_data = input_data.astype(np.float32)
        input_data = np.expand_dims(input_data, axis=0)
        if self._trans_nhwc2nchw:
            input_data = input_data.transpose(0, 3, 1, 2)  # NHWC => NCHW
        return input_data

    def get_next(self) -> list:
        """Get samples to be used in calibration

        Returns:
            ret_value: list containing dictionary data to be used in calibration.
            The dictionary must have the following key.
            - key
            - value

        Note:
            ret_value example is shown below.
            [
                {
                    "key": <input node name>
                    "value": <numpy array etc. This value depends on your model>
                },
                {
                    "key": <input node name>
                    "value": <numpy array etc. This value depends on your model>
                }
                ...
            ]
        """
        inputs = next(self._all_filepath_iter, None)
        if inputs is None:
            return None

        ret_value = []
        for i, filepath in enumerate(inputs):
            # Get input node name
            input_name = self._all_input_name[i]

            # Load image data
            if filepath.suffix.lower().endswith("npy"):
                logger.warning(f"No preprocessing functions are applied to this file: {filepath}")
                img = np.load(filepath)
            else:

                mean = self._calibration_info[input_name]["mean"]
                std = self._calibration_info[input_name]["std"]

                if self._trans_nhwc2nchw:
                    _, c, h, w = self._calibration_info[input_name]["shape"]
                else:
                    _, h, w, c = self._calibration_info[input_name]["shape"]

                _validate_channel_num(mean, c, "mean")
                _validate_channel_num(std, c, "standard deviation")

                try:
                    img = self.preprocess_func(filepath,
                                               width=w, height=h,
                                               mean=mean, std=std)
                except Exception:
                    raise RuntimeError(f"Failed to apply preprocessing to {filepath}. "
                                       "See the above error log for more details. "
                                       "Edit the `preprocess_func` of "
                                       "BackendCalibrationDataReader to match your data. "
                                       "If that does not help, please contact Renesas.")

            ret_value.append({"key": input_name,
                              "value": img})

        return ret_value

    def __len__(self):
        """Returns number of calibrate samples
        """
        return self._num_calibrate_samples

    def reset(self):
        """Reset data reader to initlize iterator.
        """
        self._all_filepath_iter = iter(self._all_file_path)

    def save_calib_data_list(self, output_dir):
        """Save file list to be used in calibration data
        """
        filename = "calibration_data_list.json"
        logger.info(f"Save {filename} to {output_dir} ...")
        os.makedirs(output_dir, exist_ok=True)

        def json_encode(obj):
            if isinstance(obj, pathlib.Path):
                return obj.as_posix()

        filepath = os.path.join(output_dir, filename)
        with open(filepath, "w") as outfile:
            json.dump(self._all_file_path, outfile, default=json_encode)


def get_rt_mod(json, params, lib_path):
    """Get runtime module

    Args:
        json:  The graph to be deployed in json format output by json graph. \
        The graph can contain operator(tvm_op) that points to the name of PackedFunc in the libmod.
        params: Dict containing the input information.
        lib_path: The path to the module file.

    Returns:
         rt_mod: Runtime graph module that can be used to execute the graph.
    """
    from tvm import runtime
    from tvm.contrib import graph_executor

    lib = runtime.load_module(lib_path)
    ctx = runtime.cpu()
    rt_mod = graph_executor.create(json, lib, ctx)
    rt_mod.set_input(**params)

    return rt_mod


def get_datareader_calibinfo(shape_dict, node_quant_configs):
    """Get calibration information to configure the datareader

    Args:
        shape_dict: The input shape to the graph.
        node_quant_configs: Dictionary containing mean and standard deviation for each nodes .

    Returns:
        calib_info: Dictionary containing mean and standard deviation to calibrate the model

    Note:
        calib_info is the following format dictionary.

        e.g. input_name -> calib_info
            {
                "<input node name>": {
                    "calibrate_sample_dir": "XXXX"
                    "mean": []
                    "std": []
                    "shape": []
                },
                "<input node name>": {
                    "calibrate_sample_dir": "XXXX"
                    "mean":[]
                    "std":[]
                    "shape":[]
                },
                ...
            }
    """
    calib_info = {}
    for key, value in shape_dict.items():
        info = None
        logger.info(f"Find {key} node config ...")
        for node in node_quant_configs:
            if node["name"] == key:
                info = node
        if info is None:
            raise RuntimeError(f"Failed to find `{key}` node config. "
                               f"Check whether quantization config has `{key}` node property. ")
        calib_info[key] = {
            "shape": value
        }
        calib_info[key].update(info)

    return calib_info


def get_quant_options(opts):
    """Get quantization options from options dictionary

    Args:
        opts: Dictionary containing quantization options that is generated from GUI interface

    Returns:
        quant_options: String containing quantization options to pass TVM API.
    """
    quant_options = ""

    quant_options += f" --calibrate_method {opts['calibrate_method']}"
    if opts["skip_preprocess"].lower() == "true":
        quant_options += " --skip_preprocess"

    quant_options += f" {opts['quant_options']}"

    if opts["calibrate_method"].lower() == "percentile":
        quant_options += f" percentile_value {opts['percentile_value']}"

    return quant_options


def save_tvm_output_as_bin(byoc_output, output_dir, prefix):
    """
    Args:
        byoc_output: Saved data.
        output_dir: Path to output directory.
        prefix: Prefix to attach the output file.
        suffix: Suffix to attach the output file.

    Returns:
        None
    """
    logger.info(f"Save data {prefix}...")
    os.makedirs(output_dir, exist_ok=True)

    if byoc_output.dtype == "float32":
        byoc_output.flatten().astype(np.float32).tofile(
            os.path.join(output_dir, f"{prefix}_ref_result_fp32.bin"))
    elif byoc_output.dtype == "float16":
        byoc_output.flatten().astype(np.float16).tofile(
            os.path.join(output_dir, f"{prefix}_ref_result_fp16.bin"))
    else:
        raise RuntimeError("Failed to save output.")


def exec_tvm_inference(data_reader, rt_mod, output_dir=None):
    """Execute inference via tvm runtime

    Args:
        data_reader: Datareader to be used in calibration
        rt_mod: Runtime graph module that can be used to execute the graph.

    Returns:
        None
    """
    count = 0
    while True:
        inputs = data_reader.get_next()
        if not inputs:
            break

        # inputs must be a dictionary type.
        # It must have the `key` and `value`.
        for input in inputs:
            _validate_datareader_inputs(input)
            rt_mod.set_input(**input)
        rt_mod.run()

        # Save
        count += 1
        if output_dir is not None:
            for i in range(rt_mod.get_num_outputs()):
                byoc_output = rt_mod.get_output(i).numpy()
                save_tvm_output_as_bin(byoc_output, output_dir, prefix=f"input{count}_out{i}")


def generate_random_data_as_npy(size: List[int],
                                mean: List[float],
                                std: List[float],
                                num_generated_data: int,
                                output_dir: str,
                                trans_nhwc2nchw: bool) -> None:
    """Generate the random data as npy format file.

    Random data is generated using the following formula:

        x = (x-mean)/std

        x: Data with a range of 0 to 255

    Args:
        size: Generated random data size
        mean: Mean
        std: Standard deviation
        num_generated_data: Number of generated data.
        output_dir: Path to directory to stored generated data.
        trans_nhwc2nchw: If True, transpose generated data from NHWC to NCHW.

    Return:
        None
    """
    assert size[0] == 1   # The dimension of batchsize must be 1.
    size_without_batch = size[1:]

    # To match the dimensions of the generated image, increase the dimensions.
    # mean.shape = [C] => mean.shape = [1,1,...,C]
    num_expansion_dim = len(size_without_batch) - 1
    if num_expansion_dim != 0:
        dim_index = np.arange(num_expansion_dim)
        mean = np.expand_dims(np.array(mean), tuple(dim_index))
        std = np.expand_dims(np.array(std), tuple(dim_index))

    # Transpose mean/std data from HWC to CHW. This process only apply when the dimention is 4.
    if trans_nhwc2nchw is True and len(size) == IMAGE_DIM_LENGTH:
        mean = mean.transpose()
        std = std.transpose()

    for i in range(num_generated_data):
        input_data = np.random.randint(0, 256, size=size_without_batch).astype(np.float32)
        input_data = input_data - mean
        input_data = input_data / std
        input_data = np.expand_dims(input_data, axis=0)
        np.save(os.path.join(output_dir, f"rand{i}.npy"), input_data)
