/***********************************************************************************************************************
* Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "sensor_algorithm_nsc.h"
#include "common_utils.h"
#include "app_definitions.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

void print_main_menu(void);

/*****************************************************************************************************************
 *  @brief      print_main_menu
 *              This function prints the user menu.
 *  @retval     none
 *  ****************************************************************************************************************/
void print_main_menu(void)
{
    APP_PRINT(MENUOPTION_MENU);

    /* Menu for User Selection */
    APP_PRINT(MENUOPTION1);
    APP_PRINT(MENUOPTION2);
}
/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    APP_PRINT(IN_NON_SECURE_REGION);
    print_main_menu();
    uint8_t readBuff[BUFF_SIZE] =  { RESET_VALUE };
    volatile bool   keep_running = true;    /* flag to stop algorithm execution when user has new input */

    while(true)
    {
        /* check if there is user manual item selection or button press on S1 */
        if (APP_CHECK_DATA)
        {

            uint32_t rByte = APP_READ(readBuff);

            /* function returns the converted integral number as an int value.*/
            int32_t inputRead = atoi((char *)readBuff);

            if (rByte > RESET_VALUE)
            {
                switch (inputRead)
                {
                    case START_IP_ALGORITHM:
                    {
                        APP_PRINT(MENUEVENT1);
                        keep_running = true;
                        while(keep_running == true)
                        {
                            sensor_algorithm_start_guard();
                            if (APP_CHECK_DATA)
                                break;

                        }

                    }
                    break;
                    case STOP_IP_ALGORITHM:
                    {
                        APP_PRINT(MENUEVENT2);
                        keep_running = false;
                        sensor_algorithm_stop_guard();

                    }
                    break;
                    default:
                    {
                        /* Menu for User Selection */
                        print_main_menu();
                    }
                    break;
                }
            }
        }
    }

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
