/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "spi_ep.h"

#if (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
bsp_ipc_semaphore_handle_t g_core_start_semaphore =
{
    .semaphore_num = 0
};
#endif

/*******************************************************************************************************************//**
 * @addtogroup r_spi_ep
 * @{
 **********************************************************************************************************************/

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    uint8_t rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};
    uint8_t converted_rtt_input = RESET_VALUE;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);
    APP_PRINT(BANNER_7);

    /* Initialize SPI driver */
    err = spi_init();

    if (FSP_SUCCESS != err)
    {   /* SPI module initialize failed */
        APP_PRINT("\r\n** SPI INIT FAILED **\r\n");
        APP_ERR_TRAP(err);
    }
    else
    {
        APP_PRINT("\r\n** SPI INIT SUCCESSFUL **\r\n");
    }

    /* Menu for user selection */
    APP_PRINT("\r\nSelect from the below Menu options\r\n");
    APP_PRINT("\r\nPress 1 for Write() and Read()");
    APP_PRINT("\r\nPress 2 for WriteRead()");
    APP_PRINT("\r\nPress 3 to Exit\r\n");

    while (EXIT != converted_rtt_input)
    {
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            converted_rtt_input = (uint8_t)atoi((char *)rByte);

            switch (converted_rtt_input)
            {
                case WRITE_AND_READ:
                    err = spi_write_and_read();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI WRITE AND READ Demo failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** SPI WRITE AND READ Demo Successful **\r\n");
                    }
                    break;
                case WRITE_READ:
                    err = spi_write_read();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("\r\n** SPI WRITE Demo failed **\r\n");
                        spi_clean_up();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI WRITE AND READ Demo Successful **\r\n");
                    }
                    break;
                case EXIT:
                    err = spi_exit_demo();
                    if (FSP_SUCCESS != err)
                    {
                        APP_PRINT("** SPI EXIT Demo failed **\r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** SPI EXIT Demo successful **\r\n");
                    }
                    break;
                default:
                    /* Menu for user selection */
                    APP_PRINT("\r\nSelect from the below Menu options\r\n");
                    APP_PRINT("\r\nPress 1 for Write() and Read()");
                    APP_PRINT("\r\nPress 2 for WriteRead()");
                    APP_PRINT("\r\nPress 3 to Exit\r\n");
                    break;
            }
            if ((WRITE_AND_READ <= converted_rtt_input) && (EXIT > converted_rtt_input))
            {
                APP_PRINT("\r\nEnter any key (other than 1,2,3) to go back to the main menu\r\n");
            }
        }
    }

    APP_PRINT(RTT_CTRL_TEXT_BRIGHT_CYAN "\r\nExiting SPI demo....\r\n" RTT_CTRL_RESET);

    /* Wake up 2nd core if this is first core and we are inside a multicore project. */
#if (0 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && !BSP_TZ_NONSECURE_BUILD

#if BSP_TZ_SECURE_BUILD
    /* Take semaphore so 2nd core can clear it */
    R_BSP_IpcSemaphoreTake(&g_core_start_semaphore);
#endif

    R_BSP_SecondaryCoreStart();

#if BSP_TZ_SECURE_BUILD
    /* Wait for 2nd core to start and clear semaphore */
    while(FSP_ERR_IN_USE == R_BSP_IpcSemaphoreTake(&g_core_start_semaphore))
    {
        ;
    }
#endif
#endif

#if (1 == _RA_CORE) && (1 == BSP_MULTICORE_PROJECT) && BSP_TZ_SECURE_BUILD
    /* Signal to 1st core that 2nd core has started */
    R_BSP_IpcSemaphoreGive(&g_core_start_semaphore);
#endif

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
