/**********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
 * THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2021,2022 Renesas Electronics Corporation. All rights reserved.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * File Name    : initial_aes_128.c
 * Version      : 1.00
 * Device(s)    : RA,RE,RX,RZ,Synergy Family
 * Description  : Key data generated by the Security Key Management Tool v1.02
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * History : DD.MM.YYYY Version  Description
 *         : 31.12.2021 1.00     First Release
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include "initial_aes_128.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Local Typedef definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Exported global variables
 *********************************************************************************************************************/
const AES128_t g_AES128 =
{
    /* uint32_t keytype; */
    0x00000000,
    /* uint32_t shared_key_number; */
    0x00000000,
    /* uint8_t wufpk[32]; */
    {
        0x71, 0xA5, 0xC6, 0xA5, 0x72, 0x0E, 0x0B, 0xC7, 0x31, 0x16, 0x4C, 0xB9, 0x6E, 0xD6, 0xA8, 0x8E,
        0x73, 0x64, 0xAC, 0x8C, 0x02, 0xBE, 0x58, 0xE1, 0x12, 0xA3, 0x27, 0x0F, 0xB9, 0x75, 0x4F, 0x57
    },
    /* uint8_t initial_vector[16]; */
    {
        0x3E, 0x97, 0x4F, 0x30, 0x0B, 0x86, 0xFC, 0x6D, 0x59, 0xC0, 0xD2, 0x1D, 0x6D, 0xCC, 0x73, 0x7B
    },
    /* uint8_t encrypted_user_key[AES128_BYTE_SIZE]; */
    {
        0x58, 0x5C, 0x8F, 0x79, 0xDB, 0x5C, 0x8E, 0xB4, 0x34, 0xBA, 0xDD, 0x4D, 0xDF, 0x90, 0xFE, 0x0D,
        0x94, 0x72, 0x94, 0x8B, 0x00, 0x14, 0x89, 0x3F, 0xC2, 0x38, 0x60, 0x82, 0x01, 0xFA, 0xE0, 0x1A
    },
    /* uint8_t crc[4]; */
    {
        0xAC, 0x6A, 0x58, 0xB0
    },
};

/**********************************************************************************************************************
 Private (static) variables and functions
 *********************************************************************************************************************/

