/**********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
 * THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2021,2022 Renesas Electronics Corporation. All rights reserved.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * File Name    : key_update_key.c
 * Version      : 1.00
 * Device(s)    : RA,RE,RX,RZ,Synergy Family
 * Description  : Key data generated by the Security Key Management Tool v1.02
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * History : DD.MM.YYYY Version  Description
 *         : 31.12.2021 1.00     First Release
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include "key_update_key.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Local Typedef definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Exported global variables
 *********************************************************************************************************************/
const KUK_t g_KUK =
{
    /* uint32_t keytype; */
    0x00000000,
    /* uint32_t shared_key_number; */
    0x00000000,
    /* uint8_t wufpk[32]; */
    {
        0x71, 0xA5, 0xC6, 0xA5, 0x72, 0x0E, 0x0B, 0xC7, 0x31, 0x16, 0x4C, 0xB9, 0x6E, 0xD6, 0xA8, 0x8E,
        0x73, 0x64, 0xAC, 0x8C, 0x02, 0xBE, 0x58, 0xE1, 0x12, 0xA3, 0x27, 0x0F, 0xB9, 0x75, 0x4F, 0x57
    },
    /* uint8_t initial_vector[16]; */
    {
        0x14, 0x58, 0x37, 0x50, 0x44, 0x84, 0x19, 0x0E, 0x15, 0x33, 0x6B, 0x75, 0x8E, 0xBC, 0xCC, 0x17
    },
    /* uint8_t encrypted_user_key[KUK_BYTE_SIZE]; */
    {
        0x10, 0x77, 0x1F, 0x65, 0x6F, 0xD5, 0x0D, 0x27, 0x2A, 0xE9, 0x4A, 0x98, 0x6B, 0x87, 0x7F, 0xFE,
        0x8F, 0x12, 0xC7, 0x47, 0x60, 0xAA, 0x2E, 0xD0, 0xA1, 0xCB, 0xDF, 0xDC, 0x38, 0x0D, 0x8E, 0xE6,
        0xD4, 0x00, 0x77, 0x54, 0x5D, 0x08, 0x7F, 0xAC, 0x20, 0x02, 0xE9, 0x09, 0x5C, 0x19, 0x81, 0x99
    },
    /* uint8_t crc[4]; */
    {
        0xCA, 0x61, 0x02, 0xEA
    },
};

/**********************************************************************************************************************
 Private (static) variables and functions
 *********************************************************************************************************************/

