/**********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
 * THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2021,2022 Renesas Electronics Corporation. All rights reserved.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * File Name    : new_aes_128.c
 * Version      : 1.00
 * Device(s)    : RA,RE,RX,RZ,Synergy Family
 * Description  : Key data generated by the Security Key Management Tool v1.02
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * History : DD.MM.YYYY Version  Description
 *         : 31.12.2021 1.00     First Release
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include "new_aes_128.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Local Typedef definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Exported global variables
 *********************************************************************************************************************/
const NEW_AES128_t g_NEW_AES128 =
{
    /* uint32_t keytype; */
    0x00000000,
    /* uint32_t shared_key_number; */
    0x00000000,
    /* uint8_t initial_vector[16]; */
    {
        0x21, 0x76, 0xFD, 0xDC, 0xF6, 0xDD, 0xA2, 0xFD, 0xB0, 0x98, 0x30, 0x6D, 0xDC, 0x25, 0x6A, 0xD7
    },
    /* uint8_t encrypted_user_key[NEW_AES128_BYTE_SIZE]; */
    {
        0xAE, 0x7B, 0x88, 0x10, 0x1A, 0x4A, 0x9A, 0x4D, 0x97, 0x20, 0x8D, 0x62, 0x12, 0x8D, 0xB2, 0x35,
        0x2F, 0xB3, 0xC2, 0xF4, 0xFC, 0xFD, 0xAC, 0x0A, 0xA6, 0x98, 0x32, 0xE7, 0x2E, 0x25, 0x02, 0x37
    },
    /* uint8_t crc[4]; */
    {
        0xB4, 0xC2, 0x29, 0xE2
    },
};

/**********************************************************************************************************************
 Private (static) variables and functions
 *********************************************************************************************************************/

