/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/
#include "hal_data.h"
#include "custom_guard.h"
/*******************************************************************************************************************//**
 * @addtogroup DOC_S_EP
 * @{
 **********************************************************************************************************************/
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {
	/* TODO: add your own code here */

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event) {
	if (BSP_WARM_START_RESET == event) {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
	}

	if (BSP_WARM_START_POST_C == event) {
		/* C runtime environment and system clocks are setup. */

		/* Configure pins. */
		R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
	}
}

#if BSP_TZ_SECURE_BUILD
/*
  Note:
  The compiler uses Registers R0 to R3 to pass parameters and return values. Registers R4 to R12 are used during function execution.The called function restores registers R4 to R12.
  Hence, if a NSC API is being used for a Secure function with more than 4 arguments, the Guard function should define a function with a different prototype that will be a funnel to handle all the arguments.
*/

/* Non secure callable function for LED1 */
BSP_CMSE_NONSECURE_ENTRY fsp_err_t led_set_guard (bsp_io_port_pin_t pin, bsp_io_level_t level)
{
	if(BSP_IO_PORT_02_PIN_07 == pin) //Only allowing access to LED1 (P207)
	{
		return R_IOPORT_PinWrite(&g_ioport_ctrl, pin, level);
	}
	else
	{
		return FSP_ERR_NOT_OPEN;
	}
}

/* Non secure callable function that returns g_doc_cfg.event */
BSP_CMSE_NONSECURE_ENTRY doc_event_t doc_cfg_event_read_guard (void)
{
    return g_doc_cfg.event;
}
#endif

//void doc_callback(doc_callback_args_t *p_args)
//{
//FSP_PARAMETER_NOT_USED(p_args);
//}

/*******************************************************************************************************************//**
 * @} (end defgroup DOC_S_EP)
 **********************************************************************************************************************/
