/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Entry function.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "gpt_timer.h"

/*******************************************************************************************************************//**
 * @addtogroup r_gpt_ep
 * @{
 **********************************************************************************************************************/

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Value to validate open state of timer instances */
extern uint8_t g_timer_open_state;
extern bool volatile g_one_shot_expired;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
	fsp_err_t err                           = FSP_SUCCESS;
	unsigned char rByte[BUF_SIZE]           = {INITIAL_VALUE};
	uint32_t read_data                      = RESET_VALUE;
	uint32_t gpt_desired_duty_cycle_percent = RESET_VALUE;
	uint32_t gpt_desired_period_ms          = RESET_VALUE;
	uint64_t period_counts                  = RESET_VALUE;
	uint32_t pclkd_freq_hz                  = RESET_VALUE;
	int32_t  one_shot_timeout               = INT32_MAX;
	fsp_pack_version_t version;

	/* Version get API for FLEX pack information */
	R_FSP_VersionGet(&version);

	/* Example Project information printed on the Console */
	APP_PRINT(BANNER_1);
	APP_PRINT(BANNER_2);
	APP_PRINT(BANNER_3,EP_VERSION);
	APP_PRINT(BANNER_4,version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
	APP_PRINT(BANNER_5);
	APP_PRINT(BANNER_6);
	APP_PRINT(EP_INFO);

	/* Print Menu option of GPT timer */
	print_timer_menu();

	while(true)
	{
		/* Process input only when the user has provided one */
		if (APP_CHECK_DATA)
		{
			/* Read First byte of data provided by the user */
			APP_READ(rByte);

			/* Conversion from input string to integer value */
			read_data = (uint32_t) (atoi((char *)rByte));

			switch (read_data)
			{
			case PERIODIC_MODE_TIMER:
			{
				/* Check the status of GPT timer in PWM mode */
				if (PWM_MODE == g_timer_open_state)
				{
					/* Close PWM Timer instance */
					deinit_gpt_timer(&g_timer_pwm_ctrl);
					APP_PRINT("PWM Timer Instance Closed, Start Periodic Timer Instance\r\n");
				}

				/* Check the status of GPT timer in One-Shot mode */
				if (ONE_SHOT_MODE == g_timer_open_state)
				{
					/* Close One-Shot GPT Timer instance */
					deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
					APP_PRINT("One-Shot GPT Timer Instance Closed, Start Periodic Timer Instance\r\n");
				}

				APP_PRINT ("\r\nEnter the desired period in millisecond "PERIOD_RANGE"\r\n");
				gpt_desired_period_ms = process_input_data();

				/* Get the source clock frequency (in Hz) */
				pclkd_freq_hz = R_FSP_SystemClockHzGet(FSP_PRIV_CLOCK_PCLKD);
				pclkd_freq_hz >>= (uint32_t)(g_timer_periodic_cfg.source_div);

				/* Convert period to PCLK counts so it can be set in hardware */
				period_counts = (uint64_t)((gpt_desired_period_ms * (pclkd_freq_hz * CLOCK_TYPE_SPECIFIER))\
				                / TIMER_UNITS_MILLISECONDS);

				/* Validate Period Count based on the user input (time period in millisecond) */
				if (GPT_MAX_PERIOD_COUNT < period_counts)
				{
					APP_ERR_PRINT ("\r\n** INVALID INPUT, DESIRED PERIOD IS OUT OF RANGE **\r\n");
				}
				else
				{
					/* Check the status of GPT timer in Periodic mode */
					if (PERIODIC_MODE != g_timer_open_state)
					{
						/* Initialize Periodic Timer */
						err = init_gpt_timer(&g_timer_periodic_ctrl, &g_timer_periodic_cfg, PERIODIC_MODE_TIMER);
						if (FSP_SUCCESS != err)
						{
							APP_ERR_PRINT("** init_gpt_timer function failed **\r\n");
							APP_ERR_TRAP(err);
						}
						APP_PRINT("Opened Timer in Periodic Mode\r\n");

						/* Start Periodic Timer */
						err = start_gpt_timer(&g_timer_periodic_ctrl);
						if (FSP_SUCCESS != err)
						{
							APP_ERR_PRINT("** start_gpt_timer function failed **\r\n");
							/* Close Periodic Timer instance */
							deinit_gpt_timer(&g_timer_periodic_ctrl);
							APP_ERR_TRAP(err);
						}
						APP_PRINT("Started Timer in Periodic Mode\r\n");
					}
					else
					{
						APP_PRINT("Periodic Timer Already Started, Update Timer Period to : %d\r\n",
						          gpt_desired_period_ms);
					}

					/* Period Set API set the desired period counts on the on-board LED */
					err = R_GPT_PeriodSet(&g_timer_periodic_ctrl, (uint32_t)period_counts);
					if (FSP_SUCCESS != err)
					{
						/* GPT Timer PeriodSet Failure message */
						APP_ERR_PRINT ("\r\n** R_GPT_PeriodSet API failed **\r\n");
						/* Close Periodic Timer instance */
						deinit_gpt_timer(&g_timer_periodic_ctrl);
						APP_ERR_TRAP(err);
					}
				}
				break;
			}

			case PWM_MODE_TIMER:
			{
				/* Check the status of GPT timer in Periodic mode */
				if ( PERIODIC_MODE == g_timer_open_state )
				{
					/* Close Periodic Timer instance */
					deinit_gpt_timer(&g_timer_periodic_ctrl);
					APP_PRINT("Periodic Timer Instance Closed, Start PWM Timer Instance\r\n");
				}

				/* Check the status of GPT timer in One-Shot mode */
				if (ONE_SHOT_MODE == g_timer_open_state)
				{
					/* Close One-Shot Timer instance */
					deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
					APP_PRINT("One-Shot Timer Instance Closed, Start PWM Timer Instance\r\n");
				}

				APP_PRINT ("\r\nEnter The Desired duty cycle in Percentage of Range 0 - 100:\r\n");
				gpt_desired_duty_cycle_percent = process_input_data();

				/* Validate duty cycle percentage */
				if (GPT_MAX_PERCENT < gpt_desired_duty_cycle_percent)
				{
					APP_ERR_PRINT ("\r\n** INVALID INPUT, DESIRED DUTY CYCLE IS OUT OF RANGE **\r\n");
				}
				else
				{
					/* Check the status of GPT timer in PWM mode */
					if (PWM_MODE != g_timer_open_state )
					{
						/* We got valid input, Initialize PWM timer */
						err = init_gpt_timer(&g_timer_pwm_ctrl, &g_timer_pwm_cfg, PWM_MODE_TIMER);
						if (FSP_SUCCESS != err)
						{
							APP_ERR_PRINT("** init_gpt_timer function failed **\r\n");
							APP_ERR_TRAP(err);
						}
						APP_PRINT("Opened Timer in PWM Mode\r\n");

						/* Start PWM Timer */
						err = start_gpt_timer(&g_timer_pwm_ctrl);
						if (FSP_SUCCESS != err)
						{
							APP_ERR_PRINT("** start_gpt_timer function failed **\r\n");
							/* Close PWM Timer instance */
							deinit_gpt_timer(&g_timer_pwm_ctrl);
							APP_ERR_TRAP(err);
						}
						APP_PRINT("Started Timer in PWM Mode\r\n");
					}
					else
					{
						/* Print duty cycle on RTT, when PWM Timer already started */
						APP_PRINT("PWM Timer Already started, Update duty cycle to: %d\r\n",
						          gpt_desired_duty_cycle_percent);
					}

					/* Set duty cycle of PWM timer */
					err = set_timer_duty_cycle((uint8_t)gpt_desired_duty_cycle_percent);
					if (FSP_SUCCESS != err)
					{
						/* GPT Timer duty cycle set failure message */
						APP_ERR_PRINT ("\r\n** set_timer_duty_cycle function failed **\r\n");
						/* Close PWM Timer instance */
						deinit_gpt_timer(&g_timer_pwm_ctrl);
						APP_ERR_TRAP(err);
					}
				}
				break;
			}

			case ONE_SHOT_MODE_TIMER:
			{
			    /* Check the status of GPT timer in Periodic mode */
			    if ( PERIODIC_MODE == g_timer_open_state )
			    {
			        /* Close Periodic Timer instance */
			        deinit_gpt_timer(&g_timer_periodic_ctrl);
			        APP_PRINT("Periodic Timer Instance Closed, Start One-Shot Timer Instance\r\n");
			    }

			    /* Check the status of GPT timer in PWM mode */
			    if (PWM_MODE == g_timer_open_state)
			    {
			        /* Close PWM Timer instance */
			        deinit_gpt_timer(&g_timer_pwm_ctrl);
			        APP_PRINT("PWM Timer Instance Closed, Start One-Shot Timer Instance\r\n");
			    }

			    /* Check the status of GPT timer in One-Shot mode */
			    if (ONE_SHOT_MODE == g_timer_open_state)
			    {
			        /* Close One-Shot Timer instance */
			        deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
			        APP_PRINT("One-Shot Timer Instance Closed, If Already Opened\r\n");
			    }

			    /* Initialize One-Shot Timer */
			    err = init_gpt_timer(&g_timer_one_shot_mode_ctrl, &g_timer_one_shot_mode_cfg, ONE_SHOT_MODE_TIMER);
			    if (FSP_SUCCESS != err)
			    {
			        APP_ERR_PRINT("** init_gpt_timer function failed **\r\n");
			        APP_ERR_TRAP(err);
			    }
			    APP_PRINT("Opened Timer in One-Shot mode\r\n");

			    /* Start One-Shot Timer */
			    err = start_gpt_timer(&g_timer_one_shot_mode_ctrl);
			    if (FSP_SUCCESS != err)
			    {
			        APP_ERR_PRINT("** start_gpt_timer function failed **\r\n");
			        /* Close One-Shot Timer instance */
			        deinit_gpt_timer(&g_timer_one_shot_mode_ctrl);
			        APP_ERR_TRAP(err);
			    }
			    APP_PRINT("Started Timer in One-Shot mode\r\n");

			    /* Wait for One-Shot mode timer to expire */
			    while (true != g_one_shot_expired)
			    {
			        /* Start checking for time out to avoid infinite loop */
			        --one_shot_timeout;
			        if (RESET_VALUE == one_shot_timeout)
			        {
			            /* We have reached to a scenario where One-Shot event did not occur */
			            APP_ERR_PRINT ("Callback event not received during One-Shot operation\r\n");
			            break;
			        }
			    }

			    if (true == g_one_shot_expired)
			    {
			        APP_PRINT("\r\nTimer Expired in One-Shot Mode\r\n");
			    }
			    g_one_shot_expired = false;
			    break;
			}

			default:
			{
				APP_PRINT("\r\nInvalid Menu Option Selected\r\n");
				break;
			}
			}

			read_data = RESET_VALUE;
			/* Reset buffer */
			memset (rByte, INITIAL_VALUE, BUF_SIZE);
			/* Print Menu option of GPT timer */
			print_timer_menu();
		}

		else
		{
			/* Do nothing */
		}
	}

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take
         * more than 6us */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup */

        /* Configure pins */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build) */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup r_gpt_ep)
 **********************************************************************************************************************/
