/**********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO
 * THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2021,2022 Renesas Electronics Corporation. All rights reserved.
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * File Name    : ra8m1_initial_aes128_key.c
 * Version      : 1.00
 * Device(s)    : RA,RE,RX,RZ,Synergy Family
 * Description  : Key data generated by the Security Key Management Tool v1.04
 *********************************************************************************************************************/
/**********************************************************************************************************************
 * History : DD.MM.YYYY Version  Description
 *         : 31.12.2021 1.00     First Release
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Includes   <System Includes> , "Project Includes"
 *********************************************************************************************************************/
#include "ra8m1_initial_aes128_key.h"

/**********************************************************************************************************************
 Macro definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Local Typedef definitions
 *********************************************************************************************************************/

/**********************************************************************************************************************
 Exported global variables
 *********************************************************************************************************************/
const RA8M1_AES128_t g_RA8M1_AES128 =
{
    /* uint32_t keytype; */
    0x00000005,
    /* uint32_t shared_key_number; */
    0x00000000,
    /* uint8_t wufpk[32]; */
    {
        0xA7, 0xBF, 0x7E, 0xB2, 0x70, 0x54, 0xD7, 0x8E, 0x07, 0xC5, 0x04, 0x29, 0x15, 0x20, 0x67, 0x8A,
        0xA7, 0xBF, 0x7E, 0xB2, 0x70, 0x54, 0xD7, 0x8E, 0x07, 0xC5, 0x04, 0x29, 0x15, 0x20, 0x67, 0x8A
    },
    /* uint8_t initial_vector[16]; */
    {
        0xF0, 0x35, 0x24, 0x6F, 0x8A, 0x28, 0xB1, 0xA6, 0xA3, 0x7B, 0x3D, 0xB2, 0xCD, 0x18, 0x71, 0xA2
    },
    /* uint8_t encrypted_user_key[RA8M1_AES128_SIZE]; */
    {
        0x33, 0x94, 0xCD, 0xE3, 0x44, 0x9E, 0xD9, 0xA4, 0xF0, 0x95, 0x81, 0xB1, 0x51, 0x46, 0x1D, 0x76,
        0x59, 0x3F, 0x79, 0xE8, 0x9B, 0x9B, 0xC9, 0x3D, 0x6A, 0x23, 0xEC, 0xEF, 0x11, 0x9E, 0xEF, 0x09
    },
    /* uint8_t crc[4]; */
    {
        0x18, 0x63, 0x7C, 0xBF
    },
};

/**********************************************************************************************************************
 Private (static) variables and functions
 *********************************************************************************************************************/

