/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "flash_lp_ep.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

uint8_t block_num_input_and_validation(uint8_t flash);

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};
    unsigned char rByte[BUFF_LEN] = {RESET_VALUE};
    uint8_t menu_input = RESET_VALUE;	/* User input for menu options */
    uint8_t block_num = RESET_VALUE;	/* User input data/code flash block number */

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor,\
              version.version_id_b.patch);
    APP_PRINT(EP_INFO);

    /* Setup MCU port settings after C runtime environment and system clocks are setup */
    R_BSP_WarmStart(BSP_WARM_START_POST_C);

    /* Menu for user selection */
    APP_PRINT("\r\nSelect from the below menu options\r\n");
    APP_PRINT("\r\nMenu");
    APP_PRINT("\r\nEnter 1 for Data Flash Operations");
    APP_PRINT("\r\nEnter 2 for Code Flash Operations\r\n");
    /* Print block range for flash operations */
    APP_PRINT(RANGE_DISPLAY);
    while (true)
    {
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            menu_input = (uint8_t) atoi((char*) rByte);
            switch (menu_input)
            {
                case DATA_FLASH_OPERATIONS:
                    block_num = block_num_input_and_validation(DATA_FLASH_OPERATIONS);
                    /* Open Flash_LP driver */
                    err = flash_lp_init();
                    /* Error handle */
                    if (FSP_SUCCESS != err)
                    {   /* Flash_LP module initialize failed */
                        APP_ERR_PRINT("\r\n ** FLASH_LP INIT FAILED ** \r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n ** FLASH_LP INIT SUCCESSFUL ** \r\n");
                    }
                    APP_PRINT("\r\n ** Performing Data Flash operations **\r\n");
                    err = flash_lp_data_flash_operations (block_num);
                    /* Error handle */
                    if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT("** Flash_LP Data Flash operations failed **  \r\n");
                        flash_lp_deinit();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n** Flash_LP Data Flash operations successful **  \r\n");
                    }
                    /* Close Flash_LP driver */
                    err = flash_lp_deinit();
                    /* Error handle */
                    if (FSP_SUCCESS != err)
                    {   /* Flash_LP module initialize failed */
                        APP_ERR_PRINT("\r\n ** FLASH_LP DE-INIT FAILED ** \r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n ** FLASH_LP DE-INIT SUCCESSFUL ** \r\n");
                    }
                    break;
                case CODE_FLASH_OPERATIONS:
                    block_num = block_num_input_and_validation (CODE_FLASH_OPERATIONS);
                    /* Open Flash_LP driver */
                    err = flash_lp_init ();
                    /* Error handle */
                    if (FSP_SUCCESS != err)
                    {   /* Flash_LP module initialize failed */
                        APP_ERR_PRINT("\r\n ** FLASH_LP INIT FAILED ** \r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n ** FLASH_LP INIT SUCCESSFUL ** \r\n");
                    }
                    APP_PRINT("\r\n ** Performing Code Flash operations **\r\n");
                    err = flash_lp_code_flash_operations (block_num);
                    /* Error handle */
                    if(FSP_ERR_INVALID_ADDRESS == err)
                    {
                        APP_ERR_PRINT("\r\n** Flash_LP Code Flash operations failed **  \r\n");
                    }
                    else if (FSP_SUCCESS != err)
                    {
                        APP_ERR_PRINT("\r\n** Flash_LP Code Flash operations failed **  \r\n");
                        flash_lp_deinit ();
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("** Flash_LP Code Flash operations Successful **  \r\n");
                    }
                    /* Close Flash_LP driver */
                    err = flash_lp_deinit ();
                    /* Error handle */
                    if (FSP_SUCCESS != err)
                    {   /* Flash_LP module initialize failed */
                        APP_ERR_PRINT("\r\n ** FLASH_LP DE-INIT FAILED ** \r\n");
                        APP_ERR_TRAP(err);
                    }
                    else
                    {
                        APP_PRINT("\r\n ** FLASH_LP DE-INIT SUCCESSFUL ** \r\n");
                    }
                    break;
                default:
                    /* Menu for user selection */
                    APP_PRINT("\r\nSelect from the below menu options\r\n");
                    APP_PRINT("\r\nMenu");
                    APP_PRINT("\r\nEnter 1 for Data Flash Operations");
                    APP_PRINT("\r\nEnter 2 for Code Flash Operations\r\n");
                    /* Print block range for flash operations */
                    APP_PRINT(RANGE_DISPLAY);
                    break;
            }
            if ((DATA_FLASH_OPERATIONS <= menu_input) && (CODE_FLASH_OPERATIONS >= menu_input))
            {
                APP_PRINT ("\r\nEnter any other key (except '1' and '2') to go back to the main menu\r\n");
            }
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * @brief       Take block number input from user and validates it w.r.t. data/code flash.
 * @param[IN]  	flash_type			    Macro for data flash or code flash.
 * @retval      block_num          	    Block number for data/code flash operations further.
 **********************************************************************************************************************/
uint8_t block_num_input_and_validation(uint8_t flash_type)
{
    uint8_t block_num = RESET_VALUE;	/* User input data/code flash block number */
    char rByte[BUFF_LEN] = {'\0'};	    /* RTT input buffer */
    unsigned num_bytes = RESET_VALUE;	/* Number of bytes read by RTT */

    /* Check whether the function is called for data flash or code flash input */
    if (DATA_FLASH_OPERATIONS == flash_type)
    {
        /* Data flash block number input and validation */
        APP_PRINT("\r\nEnter valid block number for Data-Flash operations:\r\n");

        while ((FLASH_DF_BLOCK0 >= FLASH_DF_BLOCK(block_num)) || (FLASH_DF_BLOCK_END < FLASH_DF_BLOCK(block_num)))
        {
            while (BYTES_RECEIVED_ZERO == num_bytes)
            {
                if (APP_CHECK_DATA)
                {
                    num_bytes = APP_READ(rByte);
                    if (BYTES_RECEIVED_ZERO == num_bytes)
                    {
                        APP_PRINT("\r\nInvalid Input\r\n");
                    }
                }
            }

            /* Check whether input is numerical value or not */
            if(('0' <= rByte[ARRAY_INDEX]) && ('9' >= rByte[ARRAY_INDEX]))
            {
                /* Convert block number string to integer */
                block_num = (uint8_t)atoi(rByte);
            }
            else
            {
                APP_PRINT("\r\nEntered Data-Flash block number is not valid \r\n");
                APP_PRINT("Please enter the valid block number. \r\n");
                num_bytes = RESET_VALUE;
                continue;
            }

            /* Data flash block number validation */
            if ((FLASH_DF_BLOCK0 > FLASH_DF_BLOCK(block_num)) || (FLASH_DF_BLOCK_END < FLASH_DF_BLOCK(block_num)))
            {
                APP_PRINT("\r\nEntered Data-Flash block number is not valid \r\n");
                APP_PRINT("Please enter the valid block number. \r\n");
                num_bytes = RESET_VALUE;
            }
            else
            {
                break;
            }
        }
    }
    else if (CODE_FLASH_OPERATIONS == flash_type)
    {
        /* Code flash block number input and validation */
        APP_PRINT("\r\nEnter valid block number, must be greater than 9 for code flash operations\r\n");

        while ((FLASH_CF_BLOCK10 > FLASH_CF_BLOCK(block_num)) || (FLASH_CF_BLOCK_END < FLASH_CF_BLOCK(block_num)))
        {
            while (BYTES_RECEIVED_ZERO == num_bytes)
            {
                if (APP_CHECK_DATA)
                {
                    num_bytes = APP_READ(rByte);
                    if (BYTES_RECEIVED_ZERO == num_bytes)
                    {
                        APP_PRINT("\r\nInvalid Input\r\n");
                    }
                }
            }

            /* Check whether input is numerical value or not */
            if(('0' <= rByte[ARRAY_INDEX]) && ('9' >= rByte[ARRAY_INDEX]))
            {
                if(('.' != rByte[ARRAY_INDEX + 2]) && ('.' != rByte[ARRAY_INDEX + 3]))
                {
                    /* Convert block number string to integer */
                    block_num = (uint8_t)atoi(rByte);
                }
                else
                {
                    APP_PRINT("\r\nEntered code flash block number is not valid \r\n");
                    APP_PRINT("Please enter valid block number \r\n");
                    num_bytes = RESET_VALUE;
                    continue;
                }
            }
            else
            {
                APP_PRINT("\r\nEntered code flash block number is not valid \r\n");
                APP_PRINT("Please enter valid block number \r\n");
                num_bytes = RESET_VALUE;
                continue;
            }

            /* Code flash block number validation */
            if ((FLASH_CF_BLOCK10 > FLASH_CF_BLOCK(block_num)) || (FLASH_CF_BLOCK_END < FLASH_CF_BLOCK(block_num)))
            {
                APP_PRINT("\r\nEntered code flash block number is not valid \r\n");
                APP_PRINT("Please enter valid block number \r\n");
                num_bytes = RESET_VALUE;
            }
            else
            {
                break;
            }
        }
    }
    else
    {
        /* Do nothing */
    }

    return block_num;
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take
         * more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
