/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Entry function. Contains routines to drive the RTT menu
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DISCLAIMER
 * This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products. No
 * other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
 * applicable laws, including copyright laws.
 * THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING
 * THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED. TO THE MAXIMUM
 * EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES
 * SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS
 * SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
 * Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability of
 * this software. By using this software, you agree to the additional terms and conditions found by accessing the
 * following link:
 * http://www.renesas.com/disclaimer
 *
 * Copyright (C) 2020 Renesas Electronics Corporation. All rights reserved.
 ***********************************************************************************************************************/
#include <app_definitions.h>
#include "hal_data.h"
#include "flash_access_ns.h"
#include "common_utils.h"
#include "bsp_api.h"
#include "sram_func.h"

int var_in_secure_sram_read = 0xFF;
extern bsp_leds_t g_bsp_leds;

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

static uint8_t writeBuffer[FLASH_WRITE_LENGTH];    /* buffer for flash writing */

void print_main_menu(void);

int *var_in_secure = (int*)SECURE_SRAM_WRITE_ADDR;

void print_main_menu(void)
{

	APP_PRINT(MENUOPTION_MENU);

	/* Menu for User Selection */
	APP_PRINT(MENUOPTION1);
	APP_PRINT(MENUOPTION2);
	APP_PRINT(MENUOPTION3);
	APP_PRINT(MENUOPTION4);
	APP_PRINT(MENUOPTION5);
	APP_PRINT(MENUOPTION6);
	APP_PRINT(MENUOPTION7);
	APP_PRINT(MENUOPTION8);
	APP_PRINT(MENUOPTION9);
}

static void setup_the_writeBuffer()
{
    volatile int i=0;

    for (i=0; i<FLASH_WRITE_LENGTH; i++)
            writeBuffer[i]=FLASH_WRITE_TEST_DATA;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void) {

    bool status_flash = false;
    APP_PRINT(IN_NON_SECURE_REGION);

    /* Define the units to be used with the software delay function */
    const bsp_delay_units_t bsp_delay_units = BSP_DELAY_UNITS_MILLISECONDS;
    /* Calculate the delay in terms of bsp_delay_units */
    const uint32_t delay = bsp_delay_units;

    /* Delay */
    R_BSP_SoftwareDelay(delay, bsp_delay_units);

    print_main_menu();


    #if BSP_TZ_SECURE_BUILD
        /* Enter non-secure code */
        R_BSP_NonSecureEnter();
    #endif

    uint8_t readBuff[BUFF_SIZE] =  { RESET_VALUE };

    while(true)
    {
		if (APP_CHECK_DATA)
		{

			uint32_t rByte = APP_READ(readBuff);

			/* function returns the converted integral number as an int value.*/
			int32_t inputRead = atoi((char *)readBuff);

			if (rByte > RESET_VALUE)
			{
			 	switch (inputRead)
				{
					case TEST_F_NS_READ_S_SRAM:
					{
					    APP_PRINT(MENUEVENT1);
					    R_BSP_SoftwareDelay(delay, bsp_delay_units);
						void (*FuncPointer) (void) = (void (*) (void)) SECURE_SRAM_READ_ADDR;
						/* below function call will trigger secure fault due to invalid entry point */
						FuncPointer ();
					}
					break;
					case TEST_F_NS_WRITE_SRAM:
					{
					    APP_PRINT(MENUEVENT2);
					    R_BSP_SoftwareDelay(delay, bsp_delay_units);
						/* below function call will trigger secure fault due to invalid exception return*/
						*var_in_secure = SRAM_WRITE_DATA;

					}
					break;
					case TEST_F_NS_READ_FLASH:
					{
						APP_PRINT(MENUEVENT3);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);
						void (*FuncPointer) (void) = (void (*) (void)) SECURE_FALSH_READ_ADDR;
						/* below function call will trigger secure fault due to invalid entry point */
						FuncPointer ();

					}
					break;
					case TEST_F_NS_WRITE_S_FLASH:
					{
						setup_the_writeBuffer();
						APP_PRINT(MENUEVENT4);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);
						/* Below flash write will fail as the block to be written is in secure region.
						 * g_flash0_write_guard function implemented security check which disables write to secure region.
						 */

						status_flash = flash_write_ns(FLASH_WRITE_TEST_BLOCK1, writeBuffer);
						if(true == status_flash)
						{
						  APP_PRINT(ACCESS_SUCCESSFUL);
						}
						else
						  APP_PRINT(ACCESS_UN_SUCCESSFUL);

						print_main_menu();
					}
					break;

					case TEST_F_NS_WRITE2_LOCKED_FLASH:
					{
						setup_the_writeBuffer();
						APP_PRINT(MENUEVENT5);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);

						/* Below flash write will fail as the block to be written is locked from flash programming and erasing.*/
						status_flash = flash_write_ns(FLASH_WRITE_TEST_BLOCK2, writeBuffer);

						if(true == status_flash)
						{
							APP_PRINT(ACCESS_SUCCESSFUL);
						}
						else
							APP_PRINT(ACCESS_UN_SUCCESSFUL);

						print_main_menu();
					}
					break;
					case TEST_F_NS_WRITE3_NS_FLASH:
					{
						setup_the_writeBuffer();
						APP_PRINT(MENUEVENT6);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);
						/* Below flash write will succeed as the block to be written is not locked for programming and erasing.
						 * In addition, reading Non-secure flash to confirm the write is successful is also granted
						 */
						status_flash = flash_write_ns(FLASH_WRITE_TEST_BLOCK3, (unsigned char *)writeBuffer);
						if(true == status_flash)
						{
							APP_PRINT(ACCESS_SUCCESSFUL);
						}
						else
							APP_PRINT(ACCESS_UN_SUCCESSFUL);
						print_main_menu();
					}
					break;
					case TEST_F_NS_COPY_S_FLASH:
					{
						APP_PRINT(MENUEVENT7);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);
						/* Below flash write will fail as it tries to copy from secure region FLASH_WRITE_TEST_BLOCK1 to non-secure region FLASH_WRITE_TEST_BLOCK3.
						 * g_flash0_write_guard function will catch this security breach and return false without taking the copy action.
						 */
						status_flash = flash_write_ns(FLASH_WRITE_TEST_BLOCK3, (unsigned char *)FLASH_WRITE_TEST_BLOCK1);
						if(true == status_flash)
						{
							APP_PRINT(ACCESS_SUCCESSFUL);
						}
						else
							APP_PRINT(ACCESS_UN_SUCCESSFUL);
						print_main_menu();
					}
					break;
					case TEST_SRAM_NS_READ_S_SRAM:
					{
						APP_PRINT(MENUEVENT8);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);
						/* below function call will trigger Secure Fault */
						read_secure_sram();

					}
					break;
					case TEST_SRAM_NS_WRITE_S_SRAM:
					{
						APP_PRINT(MENUEVENT9);
						R_BSP_SoftwareDelay(delay, bsp_delay_units);
						/* below function call will trigger Secure Fault */
						write_to_secure_sram();

					}
					break;
					default:
					{
						APP_PRINT(NOT_SUPPORTED);
						/* Menu for User Selection */
						print_main_menu();

					}
					break;
				}
			}

		}
    }
    while(1);

}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event) {
	if (BSP_WARM_START_RESET == event) {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
	}

	if (BSP_WARM_START_POST_C == event) {
		/* C runtime environment and system clocks are setup. */

		/* Configure pins. */
		R_IOPORT_Open(&g_ioport_ctrl, &g_bsp_pin_cfg);
	}
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
