/***********************************************************************************************************************
 * File Name    : index_html.c
 * Description  : Contain index.html definition
 ***********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2026 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

const char index_html[] =
"<!DOCTYPE html>\n"
"<html>\n"
"<head>\n"
"    <title>RA8 CEU Web Camera</title>\n"
"    <style>\n"
"        body {\n"
"            font-family: Arial, sans-serif;\n"
"            background-color: #f4f4f4;\n"
"            margin: 0;\n"
"            padding: 20px;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"            height: 95vh;\n"
"        }\n"
"        .container {\n"
"            background: #fff;\n"
"            padding: 30px;\n"
"            border-radius: 12px;\n"
"            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\n"
"            text-align: center;\n"
"        }\n"
"        h1 {\n"
"            font-size: 28px;\n"
"            margin-bottom: 20px;\n"
"            color: #333;\n"
"        }\n"
"        .camera-box {\n"
"            width: 640px;\n"
"            height: 480px;\n"
"            border-radius: 5px;\n"
"            position: relative;\n"
"            background-color: #808080;\n"
"            display: flex;\n"
"            justify-content: center;\n"
"            align-items: center;\n"
"        }\n"
"        .fps {\n"
"            position: absolute;\n"
"            bottom: 10px;\n"
"            left: 10px;\n"
"            background: rgba(0, 0, 0, 0.811);\n"
"            color: #fff;\n"
"            padding: 5px 10px;\n"
"            border-radius: 4px;\n"
"            font-size: 16px;\n"
"            font-weight: bold;\n"
"            height: 20px;\n"
"        }\n"
"        .fps p {\n"
"            margin: 0;\n"
"            text-align: justify;\n"
"        }\n"
"        img {\n"
"            display: block;\n"
"            border-radius: 5px;\n"
"        }\n"
"    </style>\n"
"    <script language=\"JavaScript\">\n"
"       document.addEventListener('DOMContentLoaded', function() {"
"           const mjpegImg = document.querySelector('img[src*=\"mjpeg\"]');"
"           let frameCount = 0;"
"           let lastTime = performance.now();"
"           let fps = 0;"
"           const fpsDisplay = document.createElement('div');"
"           fpsDisplay.style.cssText = 'position: fixed; top: 10px; right: 10px; background: rgba(0,0,0,0.7); color: lime; padding: 10px; font-family: monospace; font-size: 16px; border-radius: 5px; z-index: 9999;';"
"           fpsDisplay.textContent = 'FPS: 0';"
"           document.body.appendChild(fpsDisplay);"
"           const canvas = document.createElement('canvas');"
"           const ctx = canvas.getContext('2d');"
"           let lastImageData = null;"
"           let detectFrameIntervalId = null;"
"           let stalledWatchdogId = null;"
"           let lastFrameTick = performance.now();"
"           const STALL_TIMEOUT_MS = 5000;"
""
"           function stopCapture(reason = 'stopped') {"
"               if (detectFrameIntervalId) {"
"                   clearInterval(detectFrameIntervalId);"
"                   detectFrameIntervalId = null;"
"               }"
"               if (stalledWatchdogId) {"
"                   clearInterval(stalledWatchdogId);"
"                   stalledWatchdogId = null;"
"               }"
"               fpsDisplay.textContent = `FPS: ${Math.round(fps)} (${reason})`;"
"               console.warn('Capture FPS stopped:', reason);"
"           }"
""
"           mjpegImg.addEventListener('error', () => {"
"               stopCapture('stream error');"
"           });"
""
"           document.addEventListener('visibilitychange', () => {"
"               if (document.hidden) {"
"                   stopCapture('tab hidden');"
"               }"
"           });"
""
"           stalledWatchdogId = setInterval(() => {"
"               const now = performance.now();"
"               if (now - lastFrameTick > STALL_TIMEOUT_MS) {"
"                   stopCapture('stream stalled');"
"               }"
"           }, 1000);"
""
"           const detectFrameChange = setInterval(() => {"
"               detectFrameIntervalId = detectFrameChange;"
"               if (mjpegImg.naturalWidth > 0 && mjpegImg.naturalHeight > 0) {"
"                   canvas.width = mjpegImg.naturalWidth;"
"                   canvas.height = mjpegImg.naturalHeight;"
"                   try {"
"                       ctx.drawImage(mjpegImg, 0, 0);"
"                       const imageData = ctx.getImageData(0, 0, canvas.width, canvas.height);"
"                       if (lastImageData) {"
"                           let diff = false;"
"                           for (let i = 0; i < imageData.data.length; i += 100) {"
"                               if (imageData.data[i] !== lastImageData.data[i]) {"
"                                   diff = true;"
"                                   break;"
"                               }"
"                           }"
"                           if (diff) {"
"                               frameCount++;"
"                               lastFrameTick = performance.now();"
"                           }"
"                       }"
"                       lastImageData = imageData;"
"                       const currentTime = performance.now();"
"                       const elapsed = currentTime - lastTime;"
"                       if (elapsed >= 1000) {"
"                           fps = (frameCount / elapsed) * 1000;"
"                           fpsDisplay.textContent = `FPS: ${Math.round(fps)}`;"
"                           console.log(`Current FPS: ${Math.round(fps)}`);"
"                           frameCount = 0;"
"                           lastTime = currentTime;"
"                       }"
"                   } catch (e) {"
"                       console.error('Canvas error:', e);"
"                       stopCapture('canvas error');"
"                   }"
"               }"
"           }, 33);"
""
"           window.addEventListener('beforeunload', () => stopCapture('page unload'));"
"       });"
"    </script>\n"
"</head>\n"
"<body>\n"
"    <div class='container'>\n"
"        <h1>RA8 CEU Web Camera</h1>\n"
"        <div class='camera-box'>\n"
"            <img src=\"/mjpeg\" width=\"640\" height=\"480\" alt=\"CEU Web Camera\" >\n"
"        </div>\n"
"    </div>\n"
"</body>\n"
"</html>\n";
