/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2022 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "hal_data.h"
#include "common_utils.h"
#include "adc_periodic_scan.h"
#include <dmac_hal.h>
#include "adc_hal.h"
#include "gpt_hal.h"
#include "elc_hal.h"

/*******************************************************************************************************************//**
 * @addtogroup adc_gpt_periodic_sampling_ep
 * @{
 **********************************************************************************************************************/
FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Private Function Declaration */
static void signal_acquisition_init (void);
static void handle_error(fsp_err_t err, char *err_str, module_name_t module);

/* Extern variables */
extern uint16_t g_buffer_adc[NUM_SAMPLES];
extern volatile bool g_transfer_adc0_flag;
extern volatile bool g_transfer_adc1_flag;
extern volatile bool g_err_flag_adc1;
extern volatile bool g_err_flag_adc0;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version                 = {RESET_VALUE};
    fsp_err_t          err                     = FSP_SUCCESS;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Application Project information printed on the RTT */
    APP_PRINT (BANNER_INFO, EP_VERSION, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);

    /* Initialize the hal drivers for signal acquisition */
    signal_acquisition_init();

    APP_PRINT("\r\nADC Interleave Mode scan started...\r\n");

    /* start ADC Unit 0*/
    err = scan_start_adc(&g_adc0_ctrl);
    handle_error(err,"\r\n** start_adc for Unit 0 FAILED ** \r\n", ALL);

    /* start ADC Unit 1*/
    err = scan_start_adc(&g_adc1_ctrl);
    handle_error(err,"\r\n** start_adc for Unit 1 FAILED ** \r\n", ALL);

    /*Start gpt timer*/
    err = gpt_timer_start(&g_timer0_ctrl);
    handle_error(err,"\r\n** start gpt timer 0 FAILED ** \r\n", ALL);

    /* Check for callback event */
    while(true)
    {
        /* Check DMAC transfer completions */
        if((true == g_transfer_adc0_flag) && (true == g_transfer_adc1_flag))
        {

            /* Close elc instance */
            deinit_hal_elc(&g_elc_ctrl);

            /* Close adc instances*/
            deinit_hal_adc(&g_adc0_ctrl);
            deinit_hal_adc(&g_adc1_ctrl);

            /* Close GPT 0 instance */
            deinit_hal_gpt(&g_timer0_ctrl);

            /* Close DMAC opened instance */
            deinit_hal_dmac(&g_transfer_adc0_ctrl);
            deinit_hal_dmac(&g_transfer_adc1_ctrl);
            /* Stop Application */
            APP_COMPLETION_TRAP;
        }

        /* Check if adc 1 or 0 scan complete event is not received */
        if ((true == g_err_flag_adc0) || (true == g_err_flag_adc1))
        {
            handle_error(FSP_ERR_ABORTED,"\r\n** adc scan complete event on Unit 1 or 0 is not received  ** \r\n", ALL);
        }
        else
        {
            /* do nothing */
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * @brief       This functions initializes and enables adc, gpt, dmac and elc modules to be used as signal acquisition module.
 * @param[IN]   None
 * @retval      None
 * @retval      Any Other Error code apart from FSP_SUCCESS  Unsuccessful open.
 **********************************************************************************************************************/
static void signal_acquisition_init (void)
{
    fsp_err_t err = FSP_SUCCESS;
    transfer_info_t *p_info_tmp = NULL;

    /* Initialize all the links in the Event Link Controller */
    err = init_hal_elc(&g_elc_ctrl,&g_elc_cfg);
    handle_error(err,"\r\n** init_hal_elc failed ** \r\n", ELC_MODULE);

    /* Initialize DMAC instance and reconfigure for instance unit 0 */
    err = init_hal_dmac(&g_transfer_adc0_ctrl, &g_transfer_adc0_cfg);
    handle_error(err,"\r\n** init_hal_damc for unit 0 failed ** \r\n", ELC_DMAC0);
    /* Update the DMAC ch 0 settings */
    p_info_tmp = g_transfer_adc0_cfg.p_info;
    p_info_tmp->p_src = (void const*) &R_ADC0->ADDR[ZERO];
    p_info_tmp->p_dest = (void*) &g_buffer_adc[ZERO];
    err = dmac_hal_reconfigure(&g_transfer_adc0_ctrl, p_info_tmp);
    handle_error(err,"\r\n** dmac reconfiguration for unit 0 failed ** \r\n", ELC_DMAC0);

    /* Initialize DMAC instance and reconfigure for instance unit 1 */
    err = init_hal_dmac(&g_transfer_adc1_ctrl, &g_transfer_adc1_cfg);
    handle_error(err,"\r\n** dmac_init for unit 1 failed ** \r\n", ELC_DMAC01);
    /* Update the DMAC ch 1 settings */
    p_info_tmp = g_transfer_adc1_cfg.p_info;
    p_info_tmp->p_src = (void const*) &R_ADC1->ADDR[ZERO];
    p_info_tmp->p_dest = (void*) ((&g_buffer_adc[ZERO])+1);
    err = dmac_hal_reconfigure(&g_transfer_adc1_ctrl, p_info_tmp);
    handle_error(err,"\r\n** dmac reconfiguration for unit 1 failed ** \r\n", ELC_DMAC01);

    /* Initialize ADC Unit 0 and configure channels for it*/
    err = init_hal_adc(&g_adc0_ctrl,&g_adc0_cfg);
    handle_error(err,"\r\n** adc_init for unit 0 failed ** \r\n", ELC_DMAC_MODULE_ALL);

    err = adc_channel_config(&g_adc0_ctrl, &g_adc0_channel_cfg);
    handle_error(err,"\r\n** adc_channel_config for unit 0 failed ** \r\n", ELC_DMAC_ADC0_MODULE);

    err = init_hal_adc(&g_adc1_ctrl,&g_adc1_cfg);
    handle_error(err,"\r\n** adc_init for unit 1 failed ** \r\n", ELC_DMAC_ADC0_MODULE);

    err = adc_channel_config(&g_adc1_ctrl, &g_adc1_channel_cfg);
    handle_error(err,"\r\n** adc_channel_config for unit 1 failed ** \r\n", ELC_DMAC_ADC_MODULE_ALL);

    /* Initialize GPT timer 0 */
    err = init_hal_gpt(&g_timer0_ctrl, &g_timer0_cfg);
    handle_error(err,"\r\n** gpt_init for timer 0 failed ** \r\n", ELC_DMAC_ADC_MODULE_ALL);

    /* Enable the operation of the Event Link Controller */
    err = elc_enable(&g_elc_ctrl);
    handle_error(err,"\r\n** R_ELC_Enable failed ** \r\n", ALL);

    /* Enable transfers for adc unit 0*/
    err = dmac_enable(&g_transfer_adc0_ctrl);
    handle_error(err,"\r\n** dmac_enable for ADC unit 0 failed ** \r\n", ALL);

    /* Enable transfers for adc unit 1*/
    err = dmac_enable(&g_transfer_adc1_ctrl);
    handle_error(err,"\r\n** dmac_enable for ADC unit 1 failed ** \r\n", ALL);

}

/*******************************************************************************************************************//**
 *  @brief       Closes the ELC, DMAC, GPT and ADC module, Print and traps error.
 *  @param[IN]   status    error status
 *  @param[IN]   err_str   error string
 *  @param[IN]   module    module to be closed
 *  @retval      None
 **********************************************************************************************************************/
static void handle_error( fsp_err_t err, char *err_str, module_name_t module)
{
    if(FSP_SUCCESS != err)
    {
        switch (module)
        {
            case ELC_MODULE:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);
            }
            break;
            case ELC_DMAC0:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* close dmac instance */
                deinit_hal_dmac(&g_transfer_adc0_ctrl);
            }
            break;
            case ELC_DMAC01:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* close DMAC instances */
                deinit_hal_dmac(&g_transfer_adc0_ctrl);
                deinit_hal_dmac(&g_transfer_adc1_ctrl);
            }
            break;
            case ELC_DMAC_MODULE_ALL:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* close DMA instances */
                deinit_hal_dmac(&g_transfer_adc0_ctrl);
                deinit_hal_dmac(&g_transfer_adc1_ctrl);
            }
            break;
            case ELC_DMAC_ADC0_MODULE:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* close DMAC instances */
                deinit_hal_dmac(&g_transfer_adc0_ctrl);
                deinit_hal_dmac(&g_transfer_adc1_ctrl);

                /* close adc instance */
                deinit_hal_adc(&g_adc0_ctrl);
            }
            break;
            case ELC_DMAC_ADC_MODULE_ALL:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);

                /* close DMAC opened instance */
                deinit_hal_dmac(&g_transfer_adc0_ctrl);
                deinit_hal_dmac(&g_transfer_adc1_ctrl);

                /* close adc instance */
                deinit_hal_adc(&g_adc0_ctrl);
                deinit_hal_adc(&g_adc1_ctrl);
            }
            break;
            case ALL:
            {
                /* close elc instance */
                deinit_hal_elc(&g_elc_ctrl);

                /*close adc instances*/
                deinit_hal_adc(&g_adc0_ctrl);
                deinit_hal_adc(&g_adc1_ctrl);

                /* close GPT 0 instance */
                deinit_hal_gpt(&g_timer0_ctrl);

                /* close DMAC opened instance */
                deinit_hal_dmac(&g_transfer_adc0_ctrl);
                deinit_hal_dmac(&g_transfer_adc1_ctrl);
            }
            break;
            default:
            {
                /*do nothing */
            }
        }
        APP_PRINT(err_str);
        APP_ERR_TRAP(err);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open( &g_ioport_ctrl, &g_bsp_pin_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup adc_gpt_periodic_sampling_ep)
 **********************************************************************************************************************/
