/***********************************************************************************************************************
 * File Name    : custom_guard.c
 * Description  : custom non-secure callable function header
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#ifndef CUSTOM_GUARD_H_
#define CUSTOM_GUARD_H_
#include "hal_data.h"
/* This macro is used to enable/disable unused non-secure callable functions generated by FSP */
#define UNUSED_GUARD_ON	(0x0U)

#if BSP_TZ_SECURE_BUILD
BSP_CMSE_NONSECURE_ENTRY fsp_err_t led_set_guard (bsp_io_port_pin_t pin, bsp_io_level_t level);
BSP_CMSE_NONSECURE_ENTRY doc_event_t doc_cfg_event_read_guard (void);
#endif
#endif /* CUSTOM_GUARD_H_ */
