/***********************************************************************************************************************
 * File Name    : system_thread_entry.c
 * Description  : Contains entry function of system control.
 ***********************************************************************************************************************/
/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/

#include <guix_gen/thermostat_resources.h>
#include <guix_gen/thermostat_specifications.h>
#include "system_thread.h"
#include "system_api.h"
#include "brightness.h"
#include "system_time.h"
#include "temperature_time_thread.h"
#include "ospi_b_commands.h"

#define APP_ERR_TRAP(err)           if(err) { __asm("BKPT #0\n");} /* trap upon the error  */ // @suppress("3.9b, 3.9f, 8.4b Macro expansion")
#define GUI_MEM_SDRAM_POOL (783360U)

TX_BYTE_POOL g_guix_pool_sdram;
UCHAR g_mem_guix_pool_sdram[GUI_MEM_SDRAM_POOL] BSP_ALIGN_VARIABLE(8) BSP_PLACE_IN_SECTION(".sdram");


/* Root Window and screen pointers */
GX_WINDOW*      p_splash_screen;
GX_WINDOW*      p_settings_screen;
GX_WINDOW*      p_thermostat_screen;
GX_WINDOW*      p_mainpage_screen;
GX_WINDOW*      p_help_screen;
GX_WINDOW_ROOT* p_root;

#if 0
/* Mesage Queue*/
TX_QUEUE systen_msg_queue;
TX_BYTE_POOL   byte_pool;
static uint8_t byte_memory[BYTE_POOL_SIZE] = {'\0'};
static uint8_t queue_memory_system_obj[20] = {'\0'};
static CHAR *byte_pool_name = "system_processing_block";
#endif
/***********************************************************************************************************************
 Private functions
 ***********************************************************************************************************************/
static void system_state_init(void);
static fsp_err_t gpt_timer_PWM_setup(void);

/** Stored GUI state. */
extern system_state_t g_gui_state;

/* System Thread entry function */
void system_thread_entry(void)
{
    fsp_err_t     err            = FSP_SUCCESS;
    UINT          status         = TX_SUCCESS;
    UINT          gx_err         = GX_SUCCESS;
    /* block allocation will be done and address based message exchange happens */
    system_msg_t *p_message = NULL;
    system_msg_t hd_message;
    p_message = &hd_message;
    /* Initialize system state. */
    system_state_init();

    /* Initialize time-keeping hardware (RTC). */
    system_time_init();

    /* Initializes GUIX. */
    gx_err = gx_system_initialize();
    if(TX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Configure main display */
    gx_err = gx_studio_display_configure(DISPLAY,
                                rm_guix_port_hw_initialize,
                                LANGUAGE_ENGLISH,
                                DISPLAY_THEME_1,
                                &p_root);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Set pointer to the first buffer generated by the configuration (rm_guix_port_canvas) */
    gx_err = gx_canvas_memory_define(p_root->gx_window_root_canvas,
                            rm_guix_port_canvas,
                            p_root->gx_window_root_canvas->gx_canvas_memory_size);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Create the widget and attached to root window.*/
    gx_err = gx_studio_named_widget_create("Splash", (GX_WIDGET *) p_root, (GX_WIDGET **) &p_splash_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    gx_err = gx_studio_named_widget_create ("Settings", GX_NULL, (GX_WIDGET **) &p_settings_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }
    gx_err = gx_studio_named_widget_create ("MainPage", GX_NULL, (GX_WIDGET **) &p_mainpage_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    gx_err = gx_studio_named_widget_create ("Thermostat", GX_NULL, (GX_WIDGET **) &p_thermostat_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    gx_err = gx_studio_named_widget_create ("Help", GX_NULL, (GX_WIDGET **) &p_help_screen);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Shows the root window. */
    gx_err = gx_widget_show(p_root);
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Start GUIX */
    gx_err = gx_system_start();
    if(GX_SUCCESS != gx_err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }

    /* Set up GPT/PWM timer using for LCD back light control */
    err = gpt_timer_PWM_setup();
    if(FSP_SUCCESS != err)
    {
        APP_ERR_TRAP(FSP_ERR_ASSERTION);
    }


    while (1)
    {
        status = tx_queue_receive((TX_QUEUE*)&system_msg_queue, (VOID*)p_message, TX_WAIT_FOREVER);
        if(TX_SUCCESS != status)
        {
            APP_ERR_TRAP(FSP_ERR_ASSERTION);
        }
        switch (p_message->msg_id.event_b.class_code)
        {
            case SF_MESSAGE_EVENT_CLASS_TIME:
            {
                switch (p_message->msg_id.event_b.code)
                {
                case SF_MESSAGE_EVENT_HOUR_MODE_TOGGLE:
                    break;
                case SF_MESSAGE_EVENT_SET_TIME:
                case SF_MESSAGE_EVENT_SET_DATE:
                {
                    /* Update time */
                    /* Lock access to resource*/
                    tx_mutex_get(&g_sys_mutex, TX_WAIT_FOREVER);
                    adjust_time(&p_message->msg_payload.time_payload.time);
                    /* Get date, time */
                    R_RTC_CalendarTimeGet(&g_rtc_ctrl, &g_gui_state.time);
                    /* Send GUIX event to update time */
                    send_hmi_message(GXEVENT_MSG_TIME_UPDATE);;
                    tx_mutex_put(&g_sys_mutex);
                    break;
                }
                case SF_MESSAGE_EVENT_AM_PM_TOGGLE:
                {
                    rtc_time_t time = {0};
                    if (g_gui_state.time.tm_hour < 12)
                    {
                        time.tm_hour = 12;
                        adjust_time(&time);
                    }
                    else
                    {
                        time.tm_hour = -12;
                        adjust_time(&time);
                    }
                    /* Lock access to resource */
                    tx_mutex_get(&g_sys_mutex, TX_WAIT_FOREVER);
                    /* Send GUIX event to toggle AM/PM */
                    send_hmi_message (GXEVENT_MSG_AM_PM_TOGGLE);
                    tx_mutex_put(&g_sys_mutex);
                    break;
                }

                default:
                    break;
                }

            }
            break;

            default:
                break;

        }


        tx_thread_sleep (1);
    }
}

/*******************************************************************************************************************//**
 * @brief This function is setting up GPT/PWM timer
 * @param[in] None
 * @retval    fsp_err_t
 **********************************************************************************************************************/
static fsp_err_t gpt_timer_PWM_setup(void) // @suppress("8.1b, 8.1f Non-API function naming")
{
    fsp_err_t err = FSP_SUCCESS;
    /* Open GPT */
    err = R_GPT_Open(&g_timer_PWM_ctrl, &g_timer_PWM_cfg);
    if(FSP_SUCCESS != err)
    {
        return (err);
    }
    /* Enable GPT Timer */
    err = R_GPT_Enable(&g_timer_PWM_ctrl);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        return (err);
    }
    /* Start GPT timer */
    err = R_GPT_Start(&g_timer_PWM_ctrl);;
    if(FSP_SUCCESS != err)
    {
        return (err);
    }

    /* Set brightness (LCD backlight) level: 50 = (45+5) */
    g_gui_state.brightness = 45;
    brightness_up(&g_gui_state.brightness);

    return (err);
}


/*******************************************************************************************************************//**
 * @brief This function sends event to GUIX
 * @param[in] gx_event_message_t
 * @retval    none
 **********************************************************************************************************************/
static void system_state_init(void)
{
    /* Initialize system state */
    g_gui_state.fan_mode    = SYSTEM_FAN_MODE_AUTO;
    g_gui_state.fan_on      = false;
    g_gui_state.hour_mode   = SYSTEM_HOUR_MODE_12;
    g_gui_state.mode        = SYSTEM_MODE_OFF;
    g_gui_state.target_temp = 24;
    g_gui_state.temp_units  = SYSTEM_TEMP_UNITS_C;
}
