/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy): 25. 3.2025   Time (hh:mm): 14:21                        */
/*******************************************************************************/


#ifndef _HELLO_WORLD_DISPLAY_RESOURCES_H_
#define _HELLO_WORLD_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY 0
#define DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_24XRGB
#define DISPLAY_X_RESOLUTION 800
#define DISPLAY_Y_RESOLUTION 480
#define DISPLAY_THEME_1 0
#define DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_NEW_COLOR 29
#define GX_COLOR_ID_NEW1_COLOR 30
#define GX_COLOR_ID_NEW2_COLOR 31
#define DISPLAY_COLOR_TABLE_SIZE 32

/* Font ID definitions                                                         */

#define GX_FONT_ID_SCREENSAVER_DATE 4
#define GX_FONT_ID_SCREENSAVER_DT 5
#define GX_FONT_ID_NOTIFICATION_BAR 6
#define GX_FONT_ID_BIG_TILE_NAME 7
#define GX_FONT_ID_TILE_SMALL 8
#define GX_FONT_ID_BOLD_MENU_TITLE 9
#define GX_FONT_ID_MENU_ITEMS 10
#define GX_FONT_ID_BOLD_24 11
#define GX_FONT_ID_INDOOR_TEMP 12
#define GX_FONT_ID_SET_TO_TEMP 13
#define DISPLAY_FONT_TABLE_SIZE 14

/* Pixelmap ID definitions                                                     */

#define DISPLAY_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_CHECKBOX_TEXT 1
#define GX_STRING_ID_INSTRUCT_CHECKBOX 2
#define GX_STRING_ID_BUTTON_DISABLED 3
#define GX_STRING_ID_WINDOW1 4
#define GX_STRING_ID_HELLO_WORLD 5
#define GX_STRING_ID_WINDOW2 6
#define GX_STRING_ID_BUTTON_ENABLED 7
#define GX_STRING_ID_INSTRUCT_BUTTON 8
#define DISPLAY_STRING_TABLE_SIZE 9

#endif                                       /* sentry                         */
