/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
***********************************************************************************************************************/

#include "common_utils.h"
#include "timer_setup.h"
#include "ext_irq_setup.h"

/*******************************************************************************************************************//**
 * @addtogroup r_wdt_ep
 * @{
 **********************************************************************************************************************/

/* External global variables */

/* LED structure used to blink on board LED */
extern bsp_leds_t g_bsp_leds;
extern volatile uint8_t g_timer_underflow_counter;

/* Function declarations */

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* Private function declarations */
/* Function used to read RTT input and proceed */
static fsp_err_t read_Input_from_RTT(void);
/* Function used to enable WDT in debug mode */
static void enable_wdt_count_in_debug_mode(void);
/* Function used to check if reset is caused by WDT or not */
static void check_reset_status(void);

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used. This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_pack_version_t version = {RESET_VALUE};
    fsp_err_t err = FSP_SUCCESS;

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);

    APP_PRINT("\r\nThis example project demonstrates the typical use of the WDT HAL module APIs.");
    APP_PRINT("\r\nThe user can enter '1' through J-Link RTT Viewer to initialize the WDT and start the GPT timer.");
    APP_PRINT("\r\nThe WDT counter is refreshed periodically every 1 second when the GPT timer expires.");
    APP_PRINT("\r\nRefresh status will be printed every 3 seconds.");

#if defined (BOARD_RA2E2_EK) || defined (BOARD_RA6T1_RSSK) || defined (BOARD_RA6T2_MCK)\
    || defined (BOARD_RA6M3_EK) || defined (BOARD_RA6M3G_EK) || defined (BOARD_RA2A2_EK)\
    || defined (BOARD_RA8M1_EK) || defined (BOARD_RA8D1_EK)
    APP_PRINT("\r\nOn pressing the push button S2, the WDT counter stops from refreshing.");
#elif defined (BOARD_RA4W1_EK) || defined (BOARD_RA8E2_EK) || defined (BOARD_RA8P1_EK)\
    || defined (BOARD_RA4C1_EK)
    APP_PRINT("\r\nOn pressing the push button SW1, the WDT counter stops refreshing.");
#elif defined (BOARD_RA8T1_MCK) || defined (BOARD_RA8T2_MCK)
    APP_PRINT("\r\nOn pressing the push button on Pmod BTN, the WDT counter stops from refreshing.");
#else
    APP_PRINT("\r\nOn pressing the push button S1, the WDT counter stops refreshing.");
#endif

    APP_PRINT("\r\nAfter approximately 2 seconds, the WDT resets the MCU and turns the LED ON.\r\n");

    /* If this board has no LEDs then trap here */
    if (RESET_VALUE == g_bsp_leds.led_count)
    {
        APP_PRINT("\r\nNo on-board LEDs found");
        APP_ERR_TRAP(FSP_ERR_UNSUPPORTED);
    }

    check_reset_status();

    /* Initializing GPT in Periodic mode */
    err = init_gpt_module();
    if(FSP_SUCCESS != err)
    {
        /* Timer initialization failed */
        APP_ERR_PRINT("\r\n** GPT timer initialization failed **\r\n");
        APP_ERR_TRAP(err);
    }

    /* Initializing external IRQ */
    err = init_icu_module();
    if(FSP_SUCCESS != err)
    {
        /* External IRQ initialization failed. Cleaning up timer initialization. */
        APP_ERR_PRINT("\r\n** External IRQ initialization failed **\r\n");
        deinit_gpt_module();
        APP_ERR_TRAP(err);
    }

    /* Menu for the user selection */
    APP_PRINT("\r\nEnter '1' to enable WDT");
    APP_PRINT("\r\nUser Input:");

    while(true)
    {
        /* Process input only when the user has provided one */
        if(APP_CHECK_DATA)
        {
            err = read_Input_from_RTT();
            if(FSP_SUCCESS != err)
            {
                /* Close timer and external IRQ module */
                deinit_gpt_module();
                deinit_icu_module();
                APP_ERR_TRAP(err);
            }
        }
        /* For every 3 seconds, RTT prints WDT refresh message.
         * This is done to avoid the continuous print message on RTT */
        if (WDT_REFRESH_COUNTER_VALUE == g_timer_underflow_counter)
        {
            g_timer_underflow_counter = RESET_VALUE;
            APP_PRINT("\r\nWDT counter refreshed");
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * @brief       This function is called to read the user input from RTT using RTT API.
 *              Read the user input from RTT. Handle the error internally with proper message.
 *              Application handles the rest.
 * @param[IN]   None
 * @retval      FSP_SUCCESS     Upon successful operation.
 *              Any other error code apart from FSP_SUCCESS  Unsuccessful to perform operation.
 **********************************************************************************************************************/
fsp_err_t read_Input_from_RTT(void)
{
    fsp_err_t err = FSP_SUCCESS;     /* Error status */

    /* Variable to store the user input */
    uint8_t rByte[BUFFER_SIZE] = { RESET_VALUE };
    uint8_t user_data = RESET_VALUE;

    /* Read first byte of data provided by the user */
    APP_READ(rByte);

    user_data = (uint8_t)atoi((char *)&rByte);

    switch (user_data)
    {
        case ENABLE_WDT:
        {
            /* Enable WDT to count and generate NMI or Reset when the debugger (J-Link) is connected */
            enable_wdt_count_in_debug_mode();

            /* Open WDT. For every GPT timeout, WDT will get refreshed */
            err = R_WDT_Open(&g_wdt_ctrl, &g_wdt_cfg);
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n** R_WDT_Open API failed **\r\n");
                return err;
            }

            /* Start GPT timer in Periodic mode */
            err = timer_start();
            if (FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n** GPT timer start failed **\r\n");
                return err;
            }

            /* Enable External IRQ */
            err = enable_icu_module();
            if(FSP_SUCCESS != err)
            {
                APP_ERR_PRINT("\r\n** External IRQ enable failed **\r\n");
                return err;
            }

            /* Print message to indicate the user about application status */
            APP_PRINT("\r\nWDT initialized, GPT Timer started");
            APP_PRINT("\r\nTo stop WDT counter from refreshing, press the push button\r\n");
        }
        break;
        default:
        {
            /* Menu for the user selection */
            APP_PRINT("\r\nInvalid Input");
            APP_PRINT("\r\nPlease provide input from below option");
            APP_PRINT("\r\nEnter '1' to enable WDT");
            APP_PRINT("\r\nUser Input: ");
        }
        break;
    }
    user_data = RESET_VALUE;
    return err;
}

/*******************************************************************************************************************//**
 * @brief       This function is called to enable WDT counter in debug mode.
 *              Enables WDT counter to count in debug mode.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void enable_wdt_count_in_debug_mode(void)
{
    /* As per hardware manual's DBGREG module,
     * section 2.9.5.3:- Clear this bit to enable WDT Reset/NMI in debug mode */
    R_DEBUG->DBGSTOPCR_b.DBGSTOP_WDT = RESET_VALUE;
}

/*******************************************************************************************************************//**
 * @brief       This function is called to check whether reset is caused by WDT.
 * @param[IN]   None
 * @retval      None
 **********************************************************************************************************************/
static void check_reset_status(void)
{
    /* Check if reset was caused by the WDT? If it was, turn on LED to indicate WDT reset triggered */
    if (SYSTEM_RSTSR1_WDTRF_DETECT_WDT_RESET == R_SYSTEM->RSTSR1_b.WDTRF)
    {
        /* Clear the flag once read the value */
        R_SYSTEM->RSTSR1_b.WDTRF = RESET_VALUE;

        /* Turn ON LED */
#if defined (BOARD_RA4W1_EK) || defined (BOARD_RA6T1_RSSK) || defined (BOARD_RA6T2_MCK) || defined (BOARD_RA6T3_MCK)\
    || defined (BOARD_RA4T1_MCK) || defined (BOARD_RA8T1_MCK) || defined (BOARD_RA8T2_MCK)
        R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_bsp_leds.p_leds[0], BSP_IO_LEVEL_LOW);
#else
        R_IOPORT_PinWrite(&g_ioport_ctrl, (bsp_io_port_pin_t)g_bsp_leds.p_leds[0], BSP_IO_LEVEL_HIGH);
#endif
        APP_PRINT("\r\n************************ WDT Reset detected ************************\r\n");
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process. This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take
         * more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build
 * (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif

/*******************************************************************************************************************//**
 * @} (end addtogroup r_wdt_ep)
 **********************************************************************************************************************/
